### ISSUE TITLE
gunzip * is outputting an error code

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#101]
Here:

https://github.com/nf-core/rnafusion/blob/227cf0c62b33d512070bc015cd803e2a145eca09/download-references.nf#L120

It tries to gunzip everything and it raises an error that stops the pipeline from completing.

Changing it to `gunzip *.gz` removed the error.

**Comment by MaxUlysse** [comment]
Thanks a lot for spotting that, I'll try to fix it ASAP
