### ISSUE TITLE
.command.sh: line 3: hmmpress: command not found

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#102]
Hello!

This line contains a call to a `hmmpress` command. It appears it is not present in the newest `nfcore-rnafusion-1.1.0.img` container.

https://github.com/nf-core/rnafusion/blob/227cf0c62b33d512070bc015cd803e2a145eca09/download-references.nf#L141

**Comment by matq007** [comment]
Are you using singularity to download the references. If so, you might miss this part in the configuration:
```
withName: "star_fusion|download_star_fusion" {
    container = "${params.containerPath}/rnafusion_star-fusion_v${params.star_fusion_version}.img"
  }
```

**Comment by valleema** [comment]
Ok I am going to try and report.

BTW, I am dowloading all images, and there:
https://github.com/nf-core/rnafusion/blob/master/download-singularity-img.nf#L60-L66

There is a NF bug, as it should be `params.download_all`. Would you like me to open a new issue on this?

**Comment by MaxUlysse** [comment]
Good point, don't worry, I'll add that at my current PR #103 so no need for an issue for that

**Comment by valleema** [comment]
Ok my bad, I have tried to download references before the singularity images. It does work as intended, no `hmmpress` missing at all. Cheers!

**Comment by valleema** [comment]
Oops sorry, spoke too soon!

I have done a little loop on the images to see whether `hmmpress` is present or not.

The freshly downloaded images:
```
ls *img
nfcore-rnafusion-1.1.0.img
rnafusion_arriba_v1.1.0.img
rnafusion_ericscript_v0.5.5.img
rnafusion_fusion-inspector_v1.3.1-star2.7.0f.img
rnafusion_fusioncatcher_v1.20.img
rnafusion_pizzly_v0.37.3.img
rnafusion_squid_v1.5-star2.7.0f.img
rnafusion_star-fusion_v1.6.0.img
rnafusion_v1.1.0.img
```

```
for img in $(ls *img); do echo $img; singularity exec $img hmmpress; done
nfcore-rnafusion-1.1.0.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_arriba_v1.1.0.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_ericscript_v0.5.5.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_fusion-inspector_v1.3.1-star2.7.0f.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_fusioncatcher_v1.20.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_pizzly_v0.37.3.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_squid_v1.5-star2.7.0f.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_star-fusion_v1.6.0.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
rnafusion_v1.1.0.img
/.singularity.d/actions/exec: 9: exec: hmmpress: not found
```

As a positive test, you can see that `fusioncatcher.py` is where it is supposed to be:

```
for img in $(ls *img); do echo $img; singularity exec $img fusioncatcher.py --version; done
nfcore-rnafusion-1.1.0.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_arriba_v1.1.0.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_ericscript_v0.5.5.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_fusion-inspector_v1.3.1-star2.7.0f.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_fusioncatcher_v1.20.img
fusioncatcher.py 1.20
rnafusion_pizzly_v0.37.3.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_squid_v1.5-star2.7.0f.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_star-fusion_v1.6.0.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
rnafusion_v1.1.0.img
/.singularity.d/actions/exec: 9: exec: fusioncatcher.py: not found
```

**Comment by matq007** [comment]
Hey @valleema, we are updating the star-fusion container, should be live soon. I will let you know when it's ready. Sorry for the trouble

**Comment by valleema** [comment]
Ok I have just downloaded it and did my quick test:

```
singularity exec rnafusion_star-fusion_v1.6.0.img hmmpress
Incorrect number of command line arguments.
Usage: hmmpress [-options] <hmmfile>

To see more help on available options, do hmmpress -h

```

So far, so good. I am trying it to finish the references downloads and I will report back.

**Comment by valleema** [comment]
Ok it went farther than ever, this time I am sure :)

However, there are some typos in `example/custom-singularity.config`.

Missing closing quotes here;
https://github.com/nf-core/rnafusion/blob/769efffdfb92e1415ca69d241f6ab35d5c958a50/example/custom-singularity.config#L30
https://github.com/nf-core/rnafusion/blob/769efffdfb92e1415ca69d241f6ab35d5c958a50/example/custom-singularity.config#L31

Filename is not this one (either `nfcore-rnafusion-1.1.0.img` or `rnafusion_v1.1.0.img`, not `rnafusion_1.1.0.img`):
https://github.com/nf-core/rnafusion/blob/769efffdfb92e1415ca69d241f6ab35d5c958a50/example/custom-singularity.config#L43

`${params.containerPath}` is not set up, and `${params.containerPathCommon}` should be replaced by the former.

**Comment by MaxUlysse** [comment]
That's for spotting these typos.
I'm guessing you made your own file based on this one.
I'll fix the current `dev` branch

**Comment by MaxUlysse** [comment]
Also we're planning on doing some refactoring, so most likely configs files will change

**Comment by valleema** [comment]
> 
> 
> That's for spotting these typos.
> I'm guessing you made your own file based on this one.
> I'll fix the current `dev` branch

Oh yeah, I customised mine, works like a charm.

**Comment by MaxUlysse** [comment]
Wondefull, then I'm guessing we can close this issue ;-)

**Comment by mpozuelo-flomics** [comment]
Hi!
I'm getting this issue using the docker container and I cannot download the references
.command.sh: line 3: hmmpress: command not found
