### ISSUE TITLE
publishDir move to download references

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#105]
Hello, it's me again :)

Here, you chose to use a move strategy:
https://github.com/nf-core/rnafusion/blob/master/download-references.nf#L90

However, down the line, the fasta and gtf files are required:
https://github.com/nf-core/rnafusion/blob/master/download-references.nf#L132-L133

But they have been moved, thus creating broken symlinks.

**Comment by MaxUlysse** [comment]
I'll add that, it's already implemented within https://github.com/nf-core/sarek/ so it'll be easy to add, but that'll have to wait for a future release

**Comment by matq007** [comment]
shouldn’t `file fasta from fasta` solve this?

**Comment by MaxUlysse** [comment]
I'm guessing a `link` mode would be better in this case cf: https://www.nextflow.io/docs/latest/process.html#publishdir

**Comment by valleema** [comment]
I am not against a `copy` as it is for the singularity images. Works well with resumes.

**Comment by matq007** [comment]
I changed it because when you download all the reference it gets quite big so I thought people would appreciate more saving some storage space in advance.

**Comment by valleema** [comment]
It is true. I clean my work dir regularly, but I get it.

**Comment by MaxUlysse** [comment]
Sounds locigal indeed, I was planning of adding this params: https://github.com/nf-core/sarek/blob/dev/docs/usage.md#--publish_dir_mode that way you could choose your own mode

**Comment by valleema** [comment]
Ok I will leave it at that then. Right now, the `move` breaks the code.
