### ISSUE TITLE
Include STAR-Fusion Ensembl reference in iGenomes

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#109]
Build, compress and push to aws iGenomes.

**Comment by valleema** [comment]
Hello!
any advances on this topic? 
Cheers!

**Comment by MaxUlysse** [comment]
Hi @valleema, I'm sorry it's taking so long to make it happen.
I encountered some urgent debugging for sarek, but I'm currently uploading the file to an s3 bucket, so I'm hoping we can have it available soonish.

**Comment by valleema** [comment]
Hi @MaxUlysse ! I hope you are good during those times. Thanks for the update.

**Comment by valleema** [comment]
Hi @MaxUlysse ! Is the upload getting forward?

**Comment by MaxUlysse** [comment]
```
> aws s3 ls s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/CTAT/
2020-04-07 17:09:19 31429425612 GRCh38_gencode_v32_CTAT_lib_Dec062019.tar.xz
```

**Comment by matq007** [comment]
I will start working on refactoring the whole `download-reference.nf` this week.

**Comment by valleema** [comment]
Thanks, that's superb news
