### ISSUE TITLE
Is dev branch testable?

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#134]
Hello,

I have cloned the repo and switched to dev branch, to try updated download script.

This command does not download a file, then the rest of the commands won't work:

```
aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/Homo_sapiens/Ensembl/GRCh38/Genome/CTAT/ctat_star_fusion_1_8_1.tar.gz .
```

**Comment by matq007** [comment]
Hi @valleema, the reference is there

```
aws s3 --no-sign-request --region eu-west-1 ls s3://ngi-igenomes/Homo_sapiens/Ensembl/GRCh38/Genome/CTAT/                                                                                                                                                                                                                               253 [14:03:55]
2020-05-11 17:31:46 33090058033 ctat_star_fusion_1_8_1.tar.gz
```

Have you checked you have the latest `dev` container? The pipeline should run now without any configuration files as was previously mandatory.

**Comment by valleema** [comment]
Yes I tried the `dev` branch, but it cannot go through downloading refs, I do not understand why. I tried to create a folder, and use the same command that is in the `download_references.nf` script and it does nothing:

```
[~]=> mkdir foo
[~]=> cd foo/
[~/foo]=> aws s3 --no-sign-request ls s3://ngi-igenomes/Homo_sapiens/Ensembl/GRCh38/Genome/CTAT/ctat_star_fusion_1_8_1.tar.gz
2020-05-11 17:31:46 33090058033 ctat_star_fusion_1_8_1.tar.gz
[~/foo]=> aws s3 --no-sign-request sync s3://ngi-igenomes/Homo_sapiens/Ensembl/GRCh38/Genome/CTAT/ctat_star_fusion_1_8_1.tar.gz .
[~/foo]=> ls
[~/foo]=>
```

**Comment by MaxUlysse** [comment]
Sorry, my fault.
Did not check the command.
It should have been:
```
aws s3 --no-sign-request cp s3://ngi-igenomes/Homo_sapiens/Ensembl/GRCh38/Genome/CTAT/ctat_star_fusion_1_8_1.tar.gz .
```
`sync` is for folder, `cp` is the correct command for files.
I'll make a PR for it right away

**Comment by MaxUlysse** [comment]
@valleema Should be working now
