### ISSUE TITLE
Versions of Singularity images not retrieved on dev branch

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#136]
Hello,

I have succeeded getting all the references.

Now, I am trying to download the Singularity images. When I run the command line I am greeted by warnings:

```
nextflow run download-singularity-img.nf --outdir singularity --download_all -ansi-log false -resume
N E X T F L O W  ~  version 20.01.0
Launching `download-singularity-img.nf` [sleepy_wiles] - revision: 54adb7ab09
WARN: There's no process matching config selector: get_software_versions
WARN: There's no process matching config selector: arriba|arriba_visualization
WARN: There's no process matching config selector: ericscript
WARN: There's no process matching config selector: fusioncatcher
WARN: There's no process matching config selector: pizzly
WARN: There's no process matching config selector: squid
WARN: There's no process matching config selector: star_fusion|fusion_inspector
```

And then, in the first job that fails:

```
Docker image path: index.docker.io/nfcore/rnafusion:fusion-inspector_null
ERROR MANIFEST_UNKNOWN: manifest unknown
Cleaning up...
ERROR: pulling container failed!
```
Of course, it is not expected to have a `_null` in the place of the image version :)

--Maxime

**Comment by matq007** [comment]
Ah yes, we haven't updated the `download-singularity-img.nf`. I will update it right away. In the meantime, you can use `scripts/download-singularity-img.sh`

**Comment by valleema** [comment]
I tried `scripts/download-singularity-img.sh` but it fails as well.

It greps versions in `nextflow.config` but it all results as `false`:

https://github.com/nf-core/rnafusion/blob/dev/nextflow.config#L19-L25

**Comment by matq007** [comment]
Ahh, my bad. Should have checked it thoroughly. Fixing PR, now it should work for both
