### ISSUE TITLE
Wrong URL to Pfam-A.hmm.gz

### ISSUE THREAD

**Issue by abenjak** [nf-core/rnafusion#140]
Hello,
`download-references.nf`, line 140, has an URL mistake:

`wget -N ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz`

should be

`wget -N ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_releases/Pfam-A.hmm.gz`

(Note the s in current_release**s**.)

Cheers,
Andrej

**Comment by matq007** [comment]
Hi Andrej, thank you for catching the error. I have updated the `dev` branch. We have updated the references so that people don't have to build it anymore, we will provide it with `iGenomes`.

**Comment by abenjak** [comment]
Hello,
Now the correct URL is again the old one! (thanks EBI :facepalm:)
`ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz`

**Comment by rannick** [comment]
Fixed in next release
