### ISSUE TITLE
cdna.all.fa.gz file name prefix is wrong

### ISSUE THREAD

**Issue by abenjak** [nf-core/rnafusion#143]
Hello!

In `download-references.nf`, the `-O` of the following command is wrong:
`wget ftp://ftp.ensembl.org/pub/release-${params.reference_release}/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz -O Homo_sapiens.GRCh38_${params.reference_release}.cdna.all.fa.gz`

because it creates the prefix `Homo_sapiens.GRCh38_97` instead of `Homo_sapiens.GRCh38_r97` (note the `r` in **r**97). This will cause `pizzly`to exit with:
`Error: FASTA file not found Homo_sapiens.GRCh38_r97.cdna.all.fa.gz`

Cheers,
Andrej

**Comment by matq007** [comment]
Hi @abenjak, thank you for catching another error! Nice work 👍 . Making a fix right away 🙂
