### ISSUE TITLE
** Error, not able to find file: fusion_annot_lib.idx **  at /opt/conda/envs/nf-core-rnafusion-star-fusion_1.8.1/lib/STAR-Fusion/util/validate_ctat_genome_lib.pl line 28.

### ISSUE THREAD

**Issue by CS-GustaveRoussy** [nf-core/rnafusion#156]
Hi all,

I just cloned the 1.2.0 version of the rnafusion pipeline and I used the function to download_all the needed databases but it seems that something is lacking only for the "star_fusion" step. All the others steps with the others tools went OK :

```
Command error:
  ** Error, not able to find file: fusion_annot_lib.idx **  at /opt/conda/envs/nf-core-rnafusion-star-fusion_1.8.1/lib/STAR-Fusion/util/validate_ctat_genome_lib.pl line 28.


        ERROR, ctat genome lib: ctat_genome_lib_build_dir does not validate and may require indices to be rebuilt.

        Visit: https://github.com/STAR-Fusion/STAR-Fusion/wiki/rebuild_ctat_genome_lib_indices
        for details.
```

And the proposed "rebuild" protocol do not work => "Error, not finding required file at . named blast_pairs.dat.gz"

Someone has an hint ? I did something wrong ?

Thank you in advance

**Comment by CS-GustaveRoussy** [comment]
Here is my references folder tree : 

`references_downloaded/
├── arriba
│   ├── blacklist_hg19_hs37d5_GRCh37_2018-11-04.tsv
│   ├── blacklist_hg38_GRCh38_2018-11-04.tsv
│   ├── CREDITS
│   ├── cytobands_hg19_hs37d5_GRCh37_2018-02-23.tsv
│   ├── cytobands_hg38_GRCh38_2018-02-23.tsv
│   ├── protein_domains_hg19_hs37d5_GRCh37_2019-07-05.gff3
│   ├── protein_domains_hg19_hs37d5_GRCh37_2019-07-05.gff3.idx
│   ├── protein_domains_hg38_GRCh38_2019-07-05.gff3
│   └── protein_domains_hg38_GRCh38_2019-07-05.gff3.idx
├── databases
│   ├── cosmic.db
│   ├── fusiongdb.db
│   └── mitelman.db
├── ericscript
│   └── ericscript_db_homosapiens_ensembl84
├── fusioncatcher
│   └── human_v98
├── Homo_sapiens.GRCh38_r97.all.fa
├── Homo_sapiens.GRCh38_r97.cdna.all.fa.gz
├── Homo_sapiens.GRCh38_r97.gtf
└── star-fusion
    └── ctat_genome_lib_build_dir
`

**Comment by matq007** [comment]
Can you please try re-downloading star-fusion again and list afterwards `star-fusion/ctat_genome_lib_build_dir`?
`nextflow run nfcore/rnafusion/download-reference.nf --star_fusion`

**Comment by CS-GustaveRoussy** [comment]
Seems to be ok :-)

Thank you very much

**Comment by Dagsbio** [comment]
Hi, 

I just got the same error but downloading again does not work: 

![image](https://user-images.githubusercontent.com/23311037/106579049-85adbc00-6540-11eb-933c-41bc188e39a7.png)

**Comment by matq007** [comment]
@Dagsbio did you specify `profile` when running the command?

**Comment by Dagsbio** [comment]
Thanks matq007, that was the issue, but now I downloaded starfusion using `-profile` singularity` and when listing ctat_genome_lib_build_dir I get:

AnnotFilterRule.pm
blast_pairs.idx
fusion_annot_lib.gz
pfam_domains.dbm
PFAM.domtblout.dat.gz
ref_annot.cdna.fa.idx
ref_annot.gtf
ref_annot.gtf.gene_spans
ref_annot.gtf.mini.sortu
ref_genome.fa.fai
ref_genome.fa.nhr
trans.blast.align_coords.align_coords.dat
trans.blast.align_coords.align_coords.dbm


I tried running the pipeline again after re-downloading but I keep getting the error.

**Comment by Dagsbio** [comment]
Hi, as you said @matq007 I was re-downloading it wrongly.

Although, after succesfully re-donwloading star-fusion  I keep getting the same error when running the pipeline:
![image](https://user-images.githubusercontent.com/23311037/106604360-d254bf80-655f-11eb-91b1-7ca268f74649.png)
