### ISSUE TITLE
Problems running pipeline "Missing `fromPath` parameter"

### ISSUE THREAD

**Issue by mpozuelo-flomics** [nf-core/rnafusion#165]
Hi you all!
I was trying to run your pipeline in my data and I got this error 
`Missing 'fromPath' parameter" and the analyses never start`

The command I ran is:
`run nf-core/rnafusion -profile docker --reads '../samples/*.R{1,2}.fastq.gz'
`
I also tried adding 
`--genome GRCh38`

But it did not work.

Do you have any idea why could I get the problem?
Many thanks

**Comment by matq007** [comment]
Hi @mpozuelo-flomics, can you please provide the whole log?

**Comment by mpozuelo-flomics** [comment]
the problem was related to the references. Many thanks for you help
