### ISSUE TITLE
  Process `download_fusioncatcher` terminated with an error exit status (8)

### ISSUE THREAD

**Issue by Dagsbio** [nf-core/rnafusion#176]
Looks like fusioncatcher download links are down:

command used:

 **./nextflow run  rnafusion/download-references.nf -profile singularity --download_all  --outdir cosas_rnafusion/ --cosmic_usr user --cosmic_passwd pass**

output:
![image](https://user-images.githubusercontent.com/23311037/106491099-cfea5b00-64b6-11eb-835f-9f94e4d47670.png)

![image](https://user-images.githubusercontent.com/23311037/106491117-d37de200-64b6-11eb-9c19-07015d964ac5.png)

**Comment by matq007** [comment]
Yes, we are aware of the problem with fusioncatcher, you might have to skip this one 
Duplicate: #173

**Comment by Dagsbio** [comment]
Ah, thanks! 

I think I have a copy of that downloaded before but with a different version of singularity I reckon.

Do you think I could just copy that folder and try to make it work?

**Comment by matq007** [comment]
I am not sure, but you can try it out and see 🙂

**Comment by Dagsbio** [comment]
Apparently worked, thanks!!
