### ISSUE TITLE
build-ctat.nf: EMBL-EBI database link error

### ISSUE THREAD

**Issue by gitsblue** [nf-core/rnafusion#178]
Hi! I noticed several issues regarding the installation process, so let me share them.

(1) EMBL-EBI database link changed (build-ctat.nf)
In the build-ctat.nf, there is a ftp link to the EMBL-EBI database.
`ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_releases/Pfam-A.hmm.gz`

However, the connection failed when I run it, and I noticed that the original link is slightly different as follows:
`ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz` (release not release"s")

(2) custom-singularity.config link expired
In the [nf-core/rnafusion's usage section](https://nf-co.re/rnafusion/1.0.1/usage#running-the-pipeline-using-singularity), a sample configuation profile named custom-singularity.config was provided with the[ GitHub link](https://github.com/nf-core/rnafusion/blob/master/example/custom-singularity.config). However, it seems that the link is expired.

**Comment by MaxUlysse** [comment]
@gitsblue thanks a lot for your comments.

I tried the `build-ctat.nf` script a couple of months ago and it was working properly, so I assumed that the link has been changed, we'll be sure to update it in the next release.

The `custom-singularity.config` file was no longer useful since we simplify our configuration setup, so, we'll make sure to update our documentation as well.

**Comment by gitsblue** [comment]
Thank you for your reply.
Great! Looking forward to the next release.

**Comment by TracyBallinger** [comment]
Is there a work-around for this?  I've run the download commands myself, but am not sure how to run the prep_genome_lib.pl command.  When I run the modified .command.run,  I get an error: 
> bash .command.run
.command.sh: line 21: prep_genome_lib.pl: command not found
Any suggestions?

**Comment by MaxUlysse** [comment]
Yes, you should be able to run that command from within the container `nfcore/rnafusion:star-fusion_1.8.1`.
`rnafusion` does not provide the `prep_genome_lib.pl` script, but we provide the container that install star fusion and include this script.
