### ISSUE TITLE
Multiple sequencing runs for the same library

### ISSUE THREAD

**Issue by anshupas** [nf-core/rnafusion#179]
I have multiple sequencing runs for the same library. E.g. for sample A I have 4 different sequencing runs and hence 4 sets of fastq.gz files namely A_L1_R{1,2}.fastq.gz, A_L2_R{1,2}.fastq.gz, A_L3_R{1,2}.fastq.gz and A_L4_R{1,2}.fastq.gz. Is it possible to use the nf-core rna-fusion pipeline for such a situation? If yes, how?

**Comment by MaxUlysse** [comment]
Hi @anshupas,
Thanks a lot for your interest in this project.
We're currently not handling this case, but a merge step is definitively something that we can add in future release.

**Comment by anshupas** [comment]
Hello @MaxUlysse,
Thanks a lot for the information.
