### ISSUE TITLE
Inf value appears in the column  GeneExpr_Fused  of ericscript  

### ISSUE THREAD

**Issue by wcxiaoping** [nf-core/rnafusion#183]
Hi:
I find that sometimes, Inf value appears in the column  GeneExpr_Fused  of ericscript  like this:

PCOLCE2 C1QBP   3       142607954       -       17      5342475 -       ENSG00000163710 ENSG00000108561 5       1       13.19           inter-chromosomal       procollagen C-endopeptidase enhancer 2 [Source:HGNC Symbol;Acc:8739]    complement component 1, q subcomponent binding protein [Source:HGNC Symbol;Acc:1243]    agctcctcaggggaaactaagcgtcgagtcagacggcaccataatcgcctGCTTCCGGCGGCGCCTCAGGTCGCGGGGCGCCTAGGCCTGGGTTGTCCTT    243.28  101.8   Inf     0.9817  0.9716  0.2     0.647471145519798

Do you know why?

Thinks

**Comment by matq007** [comment]
Hi @wcxiaoping, I am not sure what could be a reason for this. You will have to ask the [author](https://sites.google.com/site/bioericscript/contacts).
