### ISSUE TITLE
Error: Execution cancelled -- Finishing pending tasks before exit

### ISSUE THREAD

**Issue by drshruti** [nf-core/rnafusion#193]
Hi,

I have been using nfcore pipeline for a while and was able to run the pipeline successfully till now.
We ususally have multiple runs of 15 and above and run it through this pipleine.
Recently, with my past couple of runs, I am facing the error of execution cancelled and it is ending abruptly. Tried resuming it again but ended  again in between to some other sample with the same error. 
So its not an issue with the sample sequence.

Thought it might be a memory issue so increased the memory to 2048 as well. Updated the docker file as well through pull command but the error still persists.

I am unable to execute the pipeline as it ends abruptly at any time.

Kindly help what could be done to trouble shoot the error.

I ahve attached the script.log for the reference.

Thanks
Shruti

[nf_core_fusion_script.log](https://github.com/nf-core/rnafusion/files/7151771/nf_core_fusion_script.log)

**Comment by matq007** [comment]
Hi @drshruti, this seems like a fusioncatcher issue. My guess would be the manually set `-Xmx18g`. It could be that with 12 cores the 18GB allocated memory is not enought.

**Comment by drshruti** [comment]
Hi @matq007 Martin ,
Thanks for the reply but it unlikely seems to be the case. The pipeline works well with 3-4 samples but if I increase the sample size to more than 5 it ends abrupltly with the above error and not at fusion catcher step but at any random step.

I am not sure if its memory issue or anything else.

**Comment by rannick** [comment]
I will close this as the code was massively refactored, using updated software, references and nf-core DSL2. This error is thus unlikely to be still current, and would need to be reopened with updated error description if happening again
