### ISSUE TITLE
EricScript and FusionCatcher DBs broken

### ISSUE THREAD

**Issue by adbeggs** [nf-core/rnafusion#197]
Hi,
I can see it is a little while since this has been updated but do you have a repo for the DBs or any other way to get them? Ericscript's DB download is particularly broken so any help would be much appreciated! 

Thanks
Andrew

**Comment by rannick** [comment]
Hi, 
The dsl2 branch has the updated links for ericscript. #196 should allow to build all DBs eventually, but it is a work in progress at the moment. If you are in a hurry, the fork for #196: rannick:dsl2_reference_building should run but be aware of all comments from the PR.

**Comment by apeltzer** [comment]
This should all be fine and works reliably in `dev` 👍🏻
