### ISSUE TITLE
starfusion: gtf vs chr.gtf

### ISSUE THREAD

**Issue by rannick** [nf-core/rnafusion#199]
starfusion reference building runs through using 
`ftp://ftp.ensembl.org/pub/release-${ensembl_version}/gtf/homo_sapiens/Homo_sapiens.${params.genome}.${ensembl_version}.chr.gtf.gz` 
but not with 
`ftp://ftp.ensembl.org/pub/release-${ensembl_version}/gtf/homo_sapiens/Homo_sapiens.${params.genome}.${ensembl_version}.gtf.gz` as gtf argument. 
Using chr.gtf for all steps leads however to a loss of annotations for unplaced or unlocalized contigs. Decision on what to use is necessary. 
- adapt starfusion to work with the original gtf?
- build both gtf and chr.gtf in parallel?

**Comment by matq007** [comment]
I think it makes sense to use `chr.gtf.gz`. I don't see how this could break other tools.

**Comment by rannick** [comment]
Agreed, nothing will break. Since there are STAR alignments for squid, STAR-fusion and arriba, it makes sense for the moment to differentiate and keep as much information as possible for arriba and squid but can be harmonized in release 2.1 maybe?
