### ISSUE TITLE
Using rnafusion without cosmic database

### ISSUE THREAD

**Issue by tijeco** [nf-core/rnafusion#215]
Is it possible to run the summary report from fusion-report without using the cosmic database? I see that fusion-report also supports Mitelman and FusionGDB. Can the pipeline be configured to only use those databases?

**Comment by rannick** [comment]
Rnafusion uses the standard fusion-report i.e. with all databases. But if you need it, it is possible to customize fusion-report to use different databases. But it needs to be done at the fusion-report software level.

**Comment by tijeco** [comment]
@rannick thanks for the quick response! I'll work on getting fusion-report to work that way on my end. 

Is there a flag in the pipeline to not run the summary?

**Comment by rannick** [comment]
You can run with `--skip_vis`. That will disable fusion-report and fusionInspector

**Comment by tijeco** [comment]
@rannick Thanks so much!
