### ISSUE TITLE
error in process "PICARD_COLLECTRNASEQMETRICS" when library type is "unstranded"

### ISSUE THREAD

**Issue by bkinnersley** [nf-core/rnafusion#222]
Hello,

I am running the latest dev version of rnafusion (b9c0dafad6) with a samplesheet containing RNA-Seq samples with strandedness of "unstranded".

I get this error with the process "PICARD_COLLECTRNASEQMETRICS":

"Argument STRAND_SPECIFICITY was missing: Argument 'STRAND_SPECIFICITY' is required"

It appears that this error is due to "strandedness" not being defined when the strandedness is "unstranded" rather than "forward" or "reverse" (https://github.com/nf-core/rnafusion/blob/dev/modules/local/picard/collectrnaseqmetrics/main.nf)

According to https://gatk.broadinstitute.org/hc/en-us/articles/360036716991-CollectRnaSeqMetrics-Picard-#--STRAND_SPECIFICITY acceptable values for STRAND_SPECIFICITY are "NONE", "FIRST_READ_TRANSCRIPTION_STRAND" or "SECOND_READ_TRANSCRIPTION_STRAND".

Would it be reasonable to alter https://github.com/nf-core/rnafusion/blob/dev/modules/local/picard/collectrnaseqmetrics/main.nf so that "strandedness" is set to "NONE" if "unstranded"?

Thanks very much

Best wishes

Ben

**Comment by rannick** [comment]
I don't have ready-available unstranded data for testing, so I would be happy to hear if the unstranded branch solves the problem.

**Comment by bkinnersley** [comment]
Thanks that solves the issue!

I think this is an unrelated issue, but to get references I initially ran the pipeline with "--build-references --all". The process "PICARD_COLLECTRNASEQMETRICS" expects the "refflat" file "Homo_sapiens.GRch38.102.chr.gtf.refflat" from folder "${genomes_base}/ensembl" but within this folder the oly "refflat" file is "ref_annot.gtf.refflat". As a temporary workaround I just copied "ref_annot.gtf.refflat" to "Homo_sapeins.GRCh38.102.chr.gtf.refflat"

**Comment by rannick** [comment]
The PR #225  should solve the refflat issue for all newly built refs. For compatibility with previously built ones, the copying you mentioned is still necessary

**Comment by rannick** [comment]
Closing as PR merged
