### ISSUE TITLE
Potential release time for 2.0.0

### ISSUE THREAD

**Issue by wudustan** [nf-core/rnafusion#224]
Hi, do you currently have any deadline for release of 2.0.0, also are there likely to be any major changes from the current `dev` branch?

Many thanks

**Comment by rannick** [comment]
Hi, I was busy last week but I am back now. However it is difficult to predict release time. I am getting more data to test with and more feedback on issues that need to be addressed. No major changes will be made, but a few bug fixes. You should be more or less fine using `dev ` with --build_starfusion, but I cannot guarantee it yet. Also, happy to get feedback on issues you might encounter

**Comment by rannick** [comment]
**Check also the nf-core channel: rnafusion on slack!**

**Comment by wudustan** [comment]
Awesome thanks.

**Comment by rannick** [comment]
Make

**Comment by apeltzer** [comment]
Here you go: https://github.com/nf-core/rnafusion/releases/tag/2.0.0
