### ISSUE TITLE
Run fusion inspector standalone on separate fusion list

### ISSUE THREAD

**Issue by tijeco** [nf-core/rnafusion#234]
### Description of feature

Currently, fusioninspector only runs on a list of fusion genes provided as output from fusionreport. It would be nice to be able to run fusioninspector on any given list of fusions with the same samplesheet and references used in this pipeline.

I've drafted a fork that does this here (https://github.com/tijeco/rnafusion/tree/fusioninspector). I can draft this into a PR if that would be helpful. 

What I've done thus far, is add a fusion_inspector_only workflow to `workflows`,  which is triggered to work in the `main.nf` with `--fusioninspector_only`. Also, the flag `--fusioninspector_file` is used in FUSIONINSPECTOR_ONLY_WORKFLOW which calls a modified version of the module FUSIONINSPECTOR_NO_META_LIST, that doesn't have the input fusion list be a tuple with meta data.

This seems to work,  but certainly not as sophisticated as it would need to be if actually folded into the pipeline. For that, I would need some assistance.

**Comment by rannick** [comment]
Closing as merged
