### ISSUE TITLE
Add extra STAR parameter for FusionCatcher and FusionInspector

### ISSUE THREAD

**Issue by maxulysse** [nf-core/rnafusion#249]
### Description of feature

For fusioncatcher, the parameter for STAR `--limitSjdbInsertNsj` default is `1000000`
We needed locally to add more, so we'd like a parameter to be able to specify that

**Comment by jun-wan** [comment]
`FusionInspector` had the same problem, needs to specify a larger number of `--limitSjdbInsertNsj`, the default is 1000000

**Comment by maxulysse** [comment]
cf https://github.com/FusionInspector/FusionInspector/issues/59

**Comment by rannick** [comment]
**FusionInspector**
rnafusion is just an interface, i.e. if FusionInspector cannot recognize the `limitSjdbInsertNsj` parameter, it is not possible to implement directly, except with meddling in the FusionInspector code itself. You can try to get this in a PR @jun-wan  if you feel like it but I would wait for the update from FusionInspector.
**FusionCatcher**
@maxulysse I need more info on how exactly you want add more, FusionCatcher has no parameter for this and uses its own STAR references/alignment. Are you running STAR separatly and running FusionCatcher starting from a certain step?

**Comment by jun-wan** [comment]
@rannick @maxulysse 
**FusionCatcher**
I could find the `--limitSjdbInsertNsj` if I run it from the singularity image

```
$ singularity exec docker.io-clinicalgenomics-fusioncatcher-1.33.img fusioncatcher.py -h 
...
...
  --limitSjdbInsertNsj=LIMITSJDBINSERTNSJ
                        This option is passed diretly to STAR aligner For more
                        info see STAR aligner regarding this option. Default
                        is '2000000'.
...
...
```
https://github.com/ndaniel/fusioncatcher/blob/8e498ecf97ca45a1691b95af8375b1d28d4ece02/bin/fusioncatcher.py#L1309-L1316
```
    parser.add_option("--limitSjdbInsertNsj",
                      action = "store",
                      type = "int",
                      dest = "limitSjdbInsertNsj",
                      default = 2000000, 
                      help = "This option is passed diretly to STAR aligner "+
                             "For more info see STAR aligner regarding this option. "
                             "Default is '%default'.")
```
to use the default, `limitSjdbInsertNsj` must be specified
https://github.com/ndaniel/fusioncatcher/blob/8e498ecf97ca45a1691b95af8375b1d28d4ece02/bin/fusioncatcher.py#L9970-L9971
```
                        if is_optparse_provided(parser,'limitSjdbInsertNsj'):
                            job.add('--limitSjdbInsertNsj',options.limitSjdbInsertNsj,kind='parameter')
```

**FusionInspector**
Just for a quick and temporary fix, I built a new image file with adding `--limitSjdbInsertNsj 2000000` into the script: `FusionInspector/util/run_FI_STAR.pl`, and it seems working. 
A new parameter `--STAR_xtra_params` is added in the 'devel' branch of FusionInspector, hopefully, the new release comes soon. https://github.com/FusionInspector/FusionInspector/blob/cac73f9a75b321b6be5215fbec5e474d7f7e1c1d/FusionInspector#L394-L399), 
```
        optional.add_argument(
            "--STAR_xtra_params",
            type=str,
            default=None,
            help="extra parameters to pass on to the STAR aligner"
        )
```

**Comment by rannick** [comment]
Merged to dev -> closing
