### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#25]
Visualization tools that are taken into consideration:
- [x] [FusionInspector](https://github.com/fusionInspector)
- [ ] [FuSpot](https://www.researchgate.net/publication/323157311_FuSpot_A_web-based_tool_for_visual_evaluation_of_fusion_candidates)
- [ ] [AGFusion](https://github.com/murphycj/AGFusion)
- [ ] [Clinker](https://github.com/Oshlack/Clinker)

**Comment by matq007** [comment]
Closing this issue for now. In future the idea will be to implement more tools.

**Comment by matq007** [comment]
https://medium.com/@Marianattestad/one-genome-browser-to-rule-them-all-cc41e2daccd7

**Comment by rannick** [comment]
Closing for now
