### ISSUE TITLE
AWS Megatests results not shown...

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rnafusion#267]
### Description of the bug

not for 2.0.0 nor for 2.1.0 -- megatests not shown: 

https://nf-co.re/rnafusion/2.0.0/results#rnafusion/results-c47ce6fdbfbbb249b23613f4713dde27e9ca2853/

**Comment by rannick** [comment]
The AWS full test should now run, but if the megatest has to be published on the nf-co.re website, I just want to point out that the references are then going to be there too and they are HEAVY (starfusion alone > 80 GB) @apeltzer @maxulysse

**Comment by apeltzer** [comment]
They are on AWS s3, results are browsable then by users. Si website is not affected 👍

**Comment by apeltzer** [comment]
should be fine now, too!
