### ISSUE TITLE
Trimming process

### ISSUE THREAD

**Issue by sssantamaria** [nf-core/rnafusion#268]
### Description of feature

I think it would be a good idea to add a new process in the pipeline with a trimming software because depending the samples the alignment is not well done without it. It may be a good idea to use: `trim_galore` software. It has an automated mode, in which it autodetects if there is any adaptor in the sample and it also has the option to specify the adaptor sequence. Moreover, it has also an option to produce a FASTQC report after the trimming, which would be great to see differences pre/post trimming.

**Comment by matthdsm** [comment]
Alternative, use `fastp` which has the same features and is much faster
