### ISSUE TITLE
Building Ref

### ISSUE THREAD

**Issue by ZWael** [nf-core/rnafusion#272]
### Description of the bug

Hello, nf-core team
It is more a how to question

i was using nf-core for some fusion analysis like this,
1) creating conda env for nf-core
```
conda create --name nf-core python=3.7 nf-core nextflow
````
2) downloading the pipeline 
````
conda activate nf-core
nf-core download rnafusion
````
so i have now a directory ``nf-core-rnafusion-2.1.0/workflow`` with ``main.nf`` file 

2) building ref (the singularity module is loaded)
````
nextflow run nf-core-rnafusion-2.1.0/workflow \
--build_references --all\
--outdir outdir \
--genomes_base  genomes_base \
--cosmic_username xxx@xxx --cosmic_passwd xxxxx
-profile singularity
````
in this step a ``genome_base`` folder is created with ensembl, fusion_report_db, fusioncatcher,  pizzy, star, and starfusion subfolders 
as noticed no arriba subfolder is created
so running the pipeline i have an error with the arriba step ``mount source /usr/local/var/lib/arriba doesn't exist`` 
and in the Input/output options i have this 

  arriba_ref                        : /usr/local/var/lib/arriba
  arriba_ref_blacklist              : /usr/local/var/lib/arriba/blacklist_hg38_GRCh38_v2.3.0.tsv.gz
  arriba_ref_protein_domain         : /usr/local/var/lib/arriba/protein_domains_hg38_GRCh38_v2.3.0.gff3

how to fix the arriba buiding ref step ?

**Comment by BarryDigby** [comment]
https://github.com/nf-core/rnafusion/blob/6ffe30435b611339999145e4b71ac59158cf1182/nextflow.config#L64

**Comment by rannick** [comment]
The next release is going to contain arriba references again. In the meantime, you can follow these steps:

- Download arriba tar.gz file from https://github.com/suhrig/arriba/releases/latest
- Extract
- Start rnafusion pipeline with:

```bash
nextflow run nf-core/rnafusion \
  --<arriba> (--<tool2> ... OR --all) \
  --input <SAMPLE_SHEET.CSV> \
  --genomes_base <PATH/TO/REFERENCES> \
  --outdir <OUTPUT/PATH> \
  --arriba_ref_blacklist <PATH/TO/ARRIBA/BLACKLIST/FILE> \
  --arriba_protein_domain <PATH/TO/ARRIBA/PROTEIN/DOMAIN/FILE> \
  --arriba_ref <PATH/TO/ARRIBA/REFERENCES/FOLDER>
```

**Comment by YeHW** [comment]
> The next release is going to contain arriba references again. In the meantime, you can follow these steps:
> 
> * Download arriba tar.gz file from https://github.com/suhrig/arriba/releases/latest
> * Extract
> * Start rnafusion pipeline with:
> 
> ```shell
> nextflow run nf-core/rnafusion \
>   --<arriba> (--<tool2> ... OR --all) \
>   --input <SAMPLE_SHEET.CSV> \
>   --genomes_base <PATH/TO/REFERENCES> \
>   --outdir <OUTPUT/PATH> \
>   --arriba_ref_blacklist <PATH/TO/ARRIBA/BLACKLIST/FILE> \
>   --arriba_protein_domain <PATH/TO/ARRIBA/PROTEIN/DOMAIN/FILE> \
>   --arriba_ref <PATH/TO/ARRIBA/REFERENCES/FOLDER>
> ```

`--arriba_ref_protein_domain` instead of `--arriba_protein_domain`
