### ISSUE TITLE
arriba errors

### ISSUE THREAD

**Issue by fangpingmu** [nf-core/rnafusion#283]
### Description of the bug

We are using singularity.

Command error:
  FATAL:   container creation failed: mount /usr/local/var/lib/arriba->/usr/local/var/lib/arriba error: while mounting /usr/local/var/lib/arriba: mount source /usr/local/var/lib/arriba doesn't exist

I find the .command.run under the Work dir.

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} SINGULARITYENV_NXF_DEBUG=${
NXF_DEBUG:=0} singularity exec -B /ix1 -B /usr/local/var/lib/arriba -B /ihome/crc/install/genomics_nextflow/nf-core-rnafusion-2.1.0/wor
kflow/bin -B "$PWD" --bind /zfs1:/zfs1 /ihome/crc/install/genomics_nextflow/nf-core-rnafusion-2.1.0/workflow/../singularity-images/depo
t.galaxyproject.org-singularity-arriba-2.3.0--haa8aa89_0.img /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash /ix1/crc/fangp
ing/nf-core-rnafusion/job2/work/c3/0197574fcb8dfc10590e6392a78847/.command.run nxf_trace"
}

"-B /usr/local/var/lib/arriba" This will bind /usr/local/var/lib/arriba on the host to the singularity container. However, /usr/local/var/lib/arriba is not available on the host. It is inside the container. 

It seems that you are trying to bind protein_domains_hg38_GRCh38_v2.3.0.gff3 to /usr/local/var/lib/arriba/protein_domains_hg38_GRCh38_v2.3.0.gff3 inside the container. 

When I shell into the singularity image, I can find protein_domains_hg38_GRCh38_v2.3.0.gff3 under /usr/local/var/lib/arriba. How can I remove "-B /usr/local/var/lib/arriba" from nxf_launch()?

[fangping@login0b singularity-images]$ singularity shell depot.galaxyproject.org-singularity-arriba-2.3.0--haa8aa89_0.img
Singularity> cd /usr/local/var/lib/arriba
Singularity> ls
CREDITS                                         fusions.tsv
RefSeq_viral_genomes_v2.3.0.fa.gz               known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz
blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz      known_fusions_hg38_GRCh38_v2.3.0.tsv.gz
blacklist_hg38_GRCh38_v2.3.0.tsv.gz             known_fusions_mm10_GRCm38_v2.3.0.tsv.gz
blacklist_mm10_GRCm38_v2.3.0.tsv.gz             known_fusions_mm39_GRCm39_v2.3.0.tsv.gz
blacklist_mm39_GRCm39_v2.3.0.tsv.gz             protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv         protein_domains_hg38_GRCh38_v2.3.0.gff3
cytobands_hg38_GRCh38_v2.3.0.tsv                protein_domains_mm10_GRCm38_v2.3.0.gff3
cytobands_mm10_GRCm38_v2.3.0.tsv                protein_domains_mm39_GRCm39_v2.3.0.gff3
cytobands_mm39_GRCm39_v2.3.0.tsv                read1.fastq.gz
download_references.sh                          read2.fastq.gz
Singularity>

### Command used and terminal output

```console
module purge
module load nextflow/22.04.3 singularity/3.9.6
export NXF_SINGULARITY_CACHEDIR=/ihome/crc/install/genomics_nextflow/nf-core-rnafusion-2.1.0/singularity-images

nextflow run /ihome/crc/install/genomics_nextflow/nf-core-rnafusion-2.1.0/workflow \
 --all \
 --genomes_base /ix1/genomics/refs/nf-core-rnafusion-2.1.0/references \
 --input samplesheet.csv --outdir results_fusion \
 -profile htc

Command error:
  FATAL:   container creation failed: mount /usr/local/var/lib/arriba->/usr/local/var/lib/arriba error: while mounting /usr/local/var/lib/arriba: mount source /usr/local/var/lib/arriba doesn't exist
```

### Relevant files

Command error:
  FATAL:   container creation failed: mount /usr/local/var/lib/arriba->/usr/local/var/lib/arriba error: while mounting /usr/local/var/lib/arriba: mount source /usr/local/var/lib/arriba doesn't exist

### System information

module load nextflow/22.04.3
HPC
slurm
Singularity
Rhel 7.9
nf-core-rnafusion-2.1.0

**Comment by YeHW** [comment]
https://github.com/nf-core/rnafusion/issues/272#issue-1334751470

**Comment by wudustan** [comment]
I downloaded the refs, put them in a folder inside `genomes-base` and ran:

```
nextflow run /.../nf-core-rnafusion/workflow -profile singularity --all \
--genomes_base /.../nf-core-rnafusion/genomes_base \
--input /.../nf-core-rnafusion/samplesheets/QCTB_pilot.csv \
--outdir /.../nf-core-rnafusion/results
--arriba_ref_blacklist /.../nf-core-rnafusion/genomes_base/arriba/blacklist_hg38_GRCh38_v2.3.0.tsv.gz \
--arriba_ref_protein_domain /.../nf-core-rnafusion/genomes_base/arriba/protein_domains_hg38_GRCh38_v2.3.0.gff3 \
--arriba_ref /.../nf-core-rnafusion/genomes_base/arriba/
```

I still get the error:

```
Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (QCTB_R048)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (QCTB_R048)` terminated with an error exit status (255)

Command executed:

  arriba \
      -x QCTB_R048.Aligned.out.bam \
      -a Homo_sapiens.GRCh38.102.all.fa \
      -g Homo_sapiens.GRCh38.102.gtf \
      -o QCTB_R048.arriba.fusions.tsv \
      -O QCTB_R048.arriba.fusions.discarded.tsv \
      -b blacklist_hg38_GRCh38_v2.3.0.tsv.gz \
       \
       \
       \
      -p protein_domains_hg38_GRCh38_v2.3.0.gff3 \


  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA":
      arriba: $(arriba -h | grep 'Version:' 2>&1 |  sed 's/Version: //')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   container creation failed: mount /usr/local/var/lib/arriba->/usr/local/var/lib/arriba error: while mounting /usr/local/var/lib/arriba: mount source /usr/local/var/lib/arriba doesn't exist
```

**Comment by wudustan** [comment]
I was able to get it to run through and output arriba result - issue i had was a silly trailing backslash typo. 

However, manually specifying arriba references in a directory outside of the container seems to break visualisation NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION

```
Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (QCTB_R057)` terminated with an error exit status (1)

Command executed:

  draw_fusions.R \
      --fusions=QCTB_R057.arriba.fusions.tsv \
      --alignments=QCTB_R057_sorted.bam \
      --output=QCTB_R057.pdf \
      --annotation=Homo_sapiens.GRCh38.102.gtf \
      --cytobands=arriba/cytobands_hg38_GRCh38_v2.1.0.tsv \
      --proteinDomains=arriba/protein_domains_hg38_GRCh38_v2.1.0.gff3

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION":
      arriba: $(arriba -h | grep 'Version:' 2>&1 |  sed 's/Version: //')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: Cannot read file: arriba/cytobands_hg38_GRCh38_v2.1.0.tsv
  Execution halted

Work dir:
  /data/scratch/DMP/UCEC/GLIOTEAM/ygrabovska/nf-core-rnafusion/work/27/390b95db69af566515c2cb83fbdd24

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


```

**Comment by apeltzer** [comment]
Weird. Got it to run through even with Visualizations, but I guess I still have the old references in there too. 

```
--arriba_ref_protein_domain protein_domains_hg38_GRCh38_v2.1.0.gff3 --arriba_ref_blacklist blacklist_hg38_GRCh38_v2.1.0.tsv.gz --arriba_ref references/arriba
```

**Comment by apeltzer** [comment]
Yeah I guess we need a proper fix for the entire thing. Looks like some stuff is broken in between.

**Comment by wudustan** [comment]
It ran fine with the old references added in. So yeh looks like it's just hard-coded to be 2.1.0 somewhere... 

Thanks for taking a look
