### ISSUE TITLE
offline-to run rnafusion

### ISSUE THREAD

**Issue by dfc-1931475** [nf-core/rnafusion#289]
### Description of feature

It`s obvious that Every time I run this pipe, I have to download everything through --build reference command. It`s time-consuming and cosmic database isn`t available to ordinary people. If is there any possible to development offline mode?

**Comment by rannick** [comment]
So you only need to run `--build_references` once, and only rebuild it when the pipeline is updated. 
About the cosmic database, the issue is identical as https://github.com/nf-core/rnafusion/issues/285, so I will close here
