### ISSUE TITLE
Errors when fusioncatcher runs

### ISSUE THREAD

**Issue by WangKang-Leo** [nf-core/rnafusion#292]
### Description of the bug

I successfully ran the pipeline except for fusioncatcher. I tried to modify "--fusioncatcher_limitSjdbInsertNsj 10000000", but it was still failed. The job "fusioncatcher" runs for more than 10 hours, then reported errors. Here I attached the log file and code. Do you have any ideas to fix it?

### Command used and terminal output

```console
module load bioinfo-tools 
module load Nextflow/21.10.6
module load nf-core/1.14 
module load iGenomes/latest
export NXF_OFFLINE='TRUE'
export NXF_HOME="/castor/project/proj_nobackup/nf-core/nf-core-rnafusion-2.1.0/workflow/"
export PATH=${NXF_HOME}:${PATH}
export NXF_TEMP=$SNIC_TMP
export NXF_LAUNCHER=$SNIC_TMP
export NXF_SINGULARITY_CACHEDIR="/castor/project/proj_nobackup/nf-core/nf-core-rnafusion-2.1.0/singularity-images/"
nextflow run /castor/project/proj_nobackup/nf-core/nf-core-rnafusion-2.1.0/workflow/main.nf \
--all \
--skip_qc true \
-profile uppmax \
--custom_config_base "/home/kangwang/nf-core/nf-core-rnafusion-2.1.0/configs" \
--project sens2022005 \
--input "/home/kangwang/nf-core/nf-core-rnafusion-2.1.0/rnafusion-data/samplesheet_test.csv" \
--genomes_base "/home/kangwang/nf-core/nf-core-rnafusion-2.1.0/rnafusion-data/references" \
--genome GRCh38 \
--outdir "/home/kangwang/nf-core/nf-core-rnafusion-2.1.0/rnafusion-results" \
-resume
```

### Relevant files

[.nextflow.log](https://github.com/nf-core/rnafusion/files/10336822/default.nextflow.log)

### System information

HPC UPPMAX (Bianca)

**Comment by rannick** [comment]
Fusioncatcher is slow. Have you had more luck running it now/with other samples @WangKang-Leo ?

**Comment by WangKang-Leo** [comment]
> Fusioncatcher is slow. Have you had more luck running it now/with other samples @WangKang-Leo ?

Yes, when I limited time to 48hr, it works now.

**Comment by rannick** [comment]
Closing at just a matter of runtime
