### ISSUE TITLE
results/get and results/arriba folders contain duplicated large files

### ISSUE THREAD

**Issue by pcantalupo** [nf-core/rnafusion#293]
### Description of the bug

I'm running v2.1.0 of the pipeline. There is a folder called `results/get` that contains Arriba discarded files. These files are exact duplicates of files by the same name that are found in `results/arriba`.  For example:

```
# showing the first two discarded files in each directory
$ ls arriba/*discarded* | head -n2
arriba/AUR1.arriba.fusions.discarded.tsv
arriba/AUR3.arriba.fusions.discarded.tsv

$ ls get/ | head -n2
AUR1.arriba.fusions.discarded.tsv
AUR3.arriba.fusions.discarded.tsv

# showing the md5sum is exactly the same for the first discarded file
$ md5sum arriba/AUR1.arriba.fusions.discarded.tsv 
9d342c59e35b3e2df3159cd6d668d9d2  arriba/AUR1.arriba.fusions.discarded.tsv

$ md5sum get/AUR1.arriba.fusions.discarded.tsv 
9d342c59e35b3e2df3159cd6d668d9d2  get/AUR1.arriba.fusions.discarded.tsv
```

Is there a purpose for this behavior?  The files are are really large 1 to 2GB so it would be more efficient if they didn't need to be duplicated by default.  I haven't checked if there are other folders/files that are duplicated in the `results` folder.

**Comment by apeltzer** [comment]
Yeah likely something we can address by adjusting the publishDir directive for that process.

**Comment by rannick** [comment]
It is solved by using channel manipulations instead of get_path/get_meta processes (merged in dev with https://github.com/nf-core/rnafusion/pull/282)
