### ISSUE TITLE
Cram compression

### ISSUE THREAD

**Issue by fevac** [nf-core/rnafusion#294]
### Description of feature

It would be nice to compress bam into cram files and skip storing the bam files. Given that there are several bam files created, it would reduce the required space considerably.

**Comment by rannick** [comment]
Totally! However there is no way to work with cram files from mapping directly and manipulate them instead of bam files: an extra step needs to be added to convert -> the bam files will still exist in the work and output directories

**Comment by apeltzer** [comment]
Solved in #311
