### ISSUE TITLE
 Process `NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by artgenko** [nf-core/rnafusion#308]
### Description of the bug

Hi
I need your help 
I couldn't find a description of the bug in troubleshooting 
I am going to use rnafusion for the analysis of RNA-Seq paired-end cancer data. First, we prepared the references (building-references-new.zip) which look fine. Then we use the nf-core/rnafusion for downloaded RNA-Seq paired end data from NCBI. Please find attached files from this run (RNA-Seq-run.zip). I could not find the file mentioned in this  comment ERROR: file not found/readable: blacklist_hg38_GRCh38_v2.3.0.tsv.gz
Thank you very much
Artur

### Command used and terminal output

```console
command
nextflow run nf-core/rnafusion --all --input /mnt/dat2/ak/nf/samples/samplesheet2.csv --genomes_base /mnt/dat2/ak/nf/result/references --outdir /mnt/dat1/ak/results -profile docker -c /home/arturko/.nextflow/assets/nf-core/rnafusion/nextflow.config

terminal output

N E X T F L O W  ~  version 22.10.6
Launching `https://github.com/nf-core/rnafusion` [friendly_crick] DSL2 - revision: 6ffe30435b [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/rnafusion v2.1.0
------------------------------------------------------
Core Nextflow options
  revision                          : master
  runName                           : friendly_crick
  containerEngine                   : docker
  launchDir                         : /mnt/dat2/ak/nf
  workDir                           : /mnt/dat2/ak/nf/work
  projectDir                        : /home/arturko/.nextflow/assets/nf-core/rnafusion
  userName                          : arturko
  profile                           : docker
  configFiles                       : /home/arturko/.nextflow/assets/nf-core/rnafusion/nextflow.config, /home/arturko/.nextflow/assets/nf-core/rnafusion/nextflow.config

Input/output options
  input                             : /mnt/dat2/ak/nf/samples/samplesheet2.csv
  outdir                            : /mnt/dat1/ak/results
  genomes_base                      : /mnt/dat2/ak/nf/result/references
  ensembl_version                   : 102
  starfusion_build                  : true
  all                               : true
  arriba_ref                        : /usr/local/var/lib/arriba
  arriba_ref_blacklist              : /usr/local/var/lib/arriba/blacklist_hg38_GRCh38_v2.3.0.tsv.gz
  arriba_ref_protein_domain         : /usr/local/var/lib/arriba/protein_domains_hg38_GRCh38_v2.3.0.gff3
  ensembl_ref                       : /mnt/dat2/ak/nf/result/references/ensembl
  fusioncatcher_limitSjdbInsertNsj  : 2000000
  fusioncatcher_ref                 : /mnt/dat2/ak/nf/result/references/fusioncatcher/human_v102
  fusioninspector_limitSjdbInsertNsj: 1000000
  fusionreport_ref                  : /mnt/dat2/ak/nf/result/references/fusion_report_db
  pizzly_ref                        : /mnt/dat2/ak/nf/result/references/pizzly/kallisto
  squid_ref                         : /mnt/dat2/ak/nf/result/references/squid
  starfusion_ref                    : /mnt/dat2/ak/nf/result/references/starfusion/ctat_genome_lib_build_dir
  starindex_ref                     : /mnt/dat2/ak/nf/result/references/star

Reference genome options
  genome                            : GRCh38
  fasta                             : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.all.fa
  gtf                               : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.gtf
  chrgtf                            : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.chr.gtf
  transcript                        : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.cdna.all.fa.gz
  refflat                           : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.chr.gtf.refflat

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/rnafusion for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.151721952

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/rnafusion/blob/master/CITATIONS.md
------------------------------------------------------
executor >  local (8)
[a3/3d6dbf] process > NFCORE_RNAFUSION:RNAFUSION:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet2.csv)   [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CAT_FASTQ                                          -
[3f/325545] process > NFCORE_RNAFUSION:RNAFUSION:FASTQC (control)                                   [100%] 1 of 1 \u2714
[3e/f20248] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:STAR_FOR_ARRIBA (control)          [100%] 1 of 1 \u2714
[28/de69ca] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_SORT_FOR_ARRIBA (control) [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_INDEX_FOR_ARRIBA          -
[d2/0bf0c4] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)                   [100%] 1 of 1, failed: 1 \u2718
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:GET_PATH_ARRIBA_FAIL               -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION               -
[df/31ae39] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:KALLISTO_QUANT (control)           [100%] 1 of 1 \u2714
[06/98fb19] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:PIZZLY (control)                   [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:STAR_FOR_SQUID                      [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_VIEW_FOR_SQUID             -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_SORT_FOR_SQUID             -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID                               -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE                      -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STAR_FOR_STARFUSION            [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION                     -
[b9/f09950] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONCATCHER_WORKFLOW:FUSIONCATCHER (control)     [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT                 -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR           -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:QUALIMAP_RNASEQ                        -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:SAMTOOLS_INDEX_FOR_QC                  -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_COLLECTRNASEQMETRICS            -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_MARKDUPLICATES                  -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CUSTOM_DUMPSOFTWAREVERSIONS                        -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:MULTIQC                                            -
Execution cancelled -- Finishing pending tasks before exit

Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)` terminated with an error exit status (1)

Command executed:

  arriba \
      -x control.Aligned.out.bam \
      -a Homo_sapiens.GRCh38.102.all.fa \
      -g Homo_sapiens.GRCh38.102.gtf \
      -o control.arriba.fusions.tsv \
      -O control.arriba.fusions.discarded.tsv \
      -b blacklist_hg38_GRCh38_v2.3.0.tsv.gz \
       \
       \
       \
      -p protein_domains_hg38_GRCh38_v2.3.0.gff3 \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA":
      arriba: $(arriba -h | grep 'Version:' 2>&1 |  sed 's/Version: //')
  END_VERSIONS

Command exit status:
  1

Command output:
  [2023-02-23T07:19:40] Launching Arriba 2.3.0

Command error:
  [2023-02-23T07:19:40] Launching Arriba 2.3.0
  ERROR: file not found/readable: blacklist_hg38_GRCh38_v2.3.0.tsv.gz

Work dir:
  /mnt/dat2/ak/nf/work/d2/0bf0c40be059666a7a2e871713d7bf

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Relevant files

[RNA-Seq-run.zip](https://github.com/nf-core/rnafusion/files/10812361/RNA-Seq-run.zip)

[building_references_new.zip](https://github.com/nf-core/rnafusion/files/10818700/building_references_new.zip)

### System information

N E X T F L O W  ~  version 22.10.6
HPC 124RAM 32 Cores, 3 x 1,8 Tb space (Dell)
local
Docker
Linux Mint
2.1

**Comment by rannick** [comment]
Hi! 
So the issues about this are already closed since the change has been made in dev, it is known and solved. I am working on a release that I hope will be out soon. In the meantime you can use the fix described in: https://github.com/nf-core/rnafusion/issues/272#issuecomment-1211706042

**Comment by artgenko** [comment]
Hi 
thank you very much for your time and help, 
I did what you suggested (https://github.com/nf-core/rnafusion/issues/272#issuecomment-1211706042)
and corrected the script

./nextflow run nf-core/rnafusion \
 --all \
 --input /mnt/dat2/ak/nf/samples/samplesheet2.csv \
 --genomes_base /mnt/dat2/ak/nf/result/references \
 --outdir /mnt/dat1/ak/results \
 -profile docker \
 --arriba_ref_blacklist /mnt/dat2/ak/nf/result/arriba_v2.3.0/database/blacklist_hg38_GRCh38_v2.3.0.tsv.gz \
 --arriba_ref_protein_domain /mnt/dat2/ak/nf/result/arriba_v2.3.0/database/protein_domains_hg38_GRCh38_v2.3.0.gff3 \
 --arriba_ref /mnt/dat2/ak/nf/result/arriba_v2.3.0 \
 -c /home/arturko/.nextflow/assets/nf-core/rnafusion/nextflow.config

but I have another issue

arturko@kloto:/mnt/dat2/ak/nf$ ./flownext.sh 
N E X T F L O W  ~  version 22.10.6
Launching `https://github.com/nf-core/rnafusion` [distracted_moriondo] DSL2 - revision: 6ffe30435b [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/rnafusion v2.1.0
------------------------------------------------------
Core Nextflow options
  revision                          : master
  runName                           : distracted_moriondo
  containerEngine                   : docker
  launchDir                         : /mnt/dat2/ak/nf
  workDir                           : /mnt/dat2/ak/nf/work
  projectDir                        : /home/arturko/.nextflow/assets/nf-core/rnafusion
  userName                          : arturko
  profile                           : docker
  configFiles                       : /home/arturko/.nextflow/assets/nf-core/rnafusion/nextflow.config, /home/arturko/.nextflow/assets/nf-core/rnafusion/nextflow.config

Input/output options
  input                             : /mnt/dat2/ak/nf/samples/samplesheet2.csv
  outdir                            : /mnt/dat1/ak/results
  genomes_base                      : /mnt/dat2/ak/nf/result/references
  ensembl_version                   : 102
  starfusion_build                  : true
  all                               : true
  arriba_ref                        : /mnt/dat2/ak/nf/result/arriba_v2.3.0
  arriba_ref_blacklist              : /mnt/dat2/ak/nf/result/arriba_v2.3.0/database/blacklist_hg38_GRCh38_v2.3.0.tsv.gz
  arriba_ref_protein_domain         : /mnt/dat2/ak/nf/result/arriba_v2.3.0/database/protein_domains_hg38_GRCh38_v2.3.0.gff3
  ensembl_ref                       : /mnt/dat2/ak/nf/result/references/ensembl
  fusioncatcher_limitSjdbInsertNsj  : 2000000
  fusioncatcher_ref                 : /mnt/dat2/ak/nf/result/references/fusioncatcher/human_v102
  fusioninspector_limitSjdbInsertNsj: 1000000
  fusionreport_ref                  : /mnt/dat2/ak/nf/result/references/fusion_report_db
  pizzly_ref                        : /mnt/dat2/ak/nf/result/references/pizzly/kallisto
  squid_ref                         : /mnt/dat2/ak/nf/result/references/squid
  starfusion_ref                    : /mnt/dat2/ak/nf/result/references/starfusion/ctat_genome_lib_build_dir
  starindex_ref                     : /mnt/dat2/ak/nf/result/references/star

Reference genome options
  genome                            : GRCh38
  fasta                             : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.all.fa
  gtf                               : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.gtf
  chrgtf                            : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.chr.gtf
  transcript                        : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.cdna.all.fa.gz
  refflat                           : /mnt/dat2/ak/nf/result/references/ensembl/Homo_sapiens.GRCh38.102.chr.gtf.refflat

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/rnafusion for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.151721952

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/rnafusion/blob/master/CITATIONS.md
------------------------------------------------------
executor >  local (21)
[fe/694a77] process > NFCORE_RNAFUSION:RNAFUSION:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet2.csv)    [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CAT_FASTQ                                           -
[75/8047ca] process > NFCORE_RNAFUSION:RNAFUSION:FASTQC (control)                                    [100%] 1 of 1 \u2714
[3a/79eef2] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:STAR_FOR_ARRIBA (control)           [100%] 1 of 1 \u2714
[45/93fbda] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_SORT_FOR_ARRIBA (control)  [100%] 1 of 1 \u2714
[4e/88f15e] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_INDEX_FOR_ARRIBA (control) [100%] 1 of 1 \u2714
[96/a63807] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)                    [100%] 1 of 1 \u2714
[70/ed269f] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:GET_PATH_ARRIBA_FAIL (getpath)      [100%] 1 of 1 \u2714
[de/c55c2c] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (control)      [  0%] 0 of 1
[94/0247f1] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:KALLISTO_QUANT (control)            [100%] 1 of 1 \u2714
[c4/ed347c] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:PIZZLY (control)                    [100%] 1 of 1 \u2714
[31/313779] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:STAR_FOR_SQUID (control)             [100%] 1 of 1 \u2714
[98/37c4ee] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_VIEW_FOR_SQUID (control)    [100%] 1 of 1 \u2714
[65/933016] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_SORT_FOR_SQUID (control)    [100%] 1 of 1 \u2714
[f2/236cad] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID (squid)                        [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE                       -
[a0/da0621] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STAR_FOR_STARFUSION (control)   [100%] 1 of 1 \u2714
[48/25eb97] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION (control)            [100%] 1 of 1 \u2714
[a4/7e45be] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONCATCHER_WORKFLOW:FUSIONCATCHER (control)      [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT                  -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR            -
[ce/bd3c56] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:QUALIMAP_RNASEQ (control)               [100%] 1 of 1 \u2714
[45/b2c955] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:SAMTOOLS_INDEX_FOR_QC (control)         [100%] 1 of 1 \u2714
[fd/6bd94d] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_COLLECTRNASEQMETRICS (control)   [  0%] 0 of 1
[94/d9ba16] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_MARKDUPLICATES (control)         [100%] 1 of 1 \u2714
executor >  local (21)
[fe/694a77] process > NFCORE_RNAFUSION:RNAFUSION:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet2.csv)    [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CAT_FASTQ                                           -
[75/8047ca] process > NFCORE_RNAFUSION:RNAFUSION:FASTQC (control)                                    [100%] 1 of 1 \u2714
[3a/79eef2] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:STAR_FOR_ARRIBA (control)           [100%] 1 of 1 \u2714
[45/93fbda] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_SORT_FOR_ARRIBA (control)  [100%] 1 of 1 \u2714
[4e/88f15e] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_INDEX_FOR_ARRIBA (control) [100%] 1 of 1 \u2714
[96/a63807] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)                    [100%] 1 of 1 \u2714
[70/ed269f] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:GET_PATH_ARRIBA_FAIL (getpath)      [100%] 1 of 1 \u2714
[de/c55c2c] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (control)      [100%] 1 of 1, failed: 1 \u2718
[94/0247f1] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:KALLISTO_QUANT (control)            [100%] 1 of 1 \u2714
[c4/ed347c] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:PIZZLY (control)                    [100%] 1 of 1 \u2714
[31/313779] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:STAR_FOR_SQUID (control)             [100%] 1 of 1 \u2714
[98/37c4ee] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_VIEW_FOR_SQUID (control)    [100%] 1 of 1 \u2714
[65/933016] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_SORT_FOR_SQUID (control)    [100%] 1 of 1 \u2714
[f2/236cad] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID (squid)                        [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE                       -
[a0/da0621] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STAR_FOR_STARFUSION (control)   [100%] 1 of 1 \u2714
[48/25eb97] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION (control)            [100%] 1 of 1 \u2714
[a4/7e45be] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONCATCHER_WORKFLOW:FUSIONCATCHER (control)      [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT                  -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR            -
[ce/bd3c56] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:QUALIMAP_RNASEQ (control)               [100%] 1 of 1 \u2714
[45/b2c955] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:SAMTOOLS_INDEX_FOR_QC (control)         [100%] 1 of 1 \u2714
[fd/6bd94d] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_COLLECTRNASEQMETRICS (control)   [  0%] 0 of 1
[94/d9ba16] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_MARKDUPLICATES (control)         [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CUSTOM_DUMPSOFTWAREVERSIONS                         -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:MULTIQC                                             -
Execution cancelled -- Finishing pending tasks before exit
executor >  local (21)
[fe/694a77] process > NFCORE_RNAFUSION:RNAFUSION:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet2.csv)    [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CAT_FASTQ                                           -
[75/8047ca] process > NFCORE_RNAFUSION:RNAFUSION:FASTQC (control)                                    [100%] 1 of 1 \u2714
[3a/79eef2] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:STAR_FOR_ARRIBA (control)           [100%] 1 of 1 \u2714
[45/93fbda] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_SORT_FOR_ARRIBA (control)  [100%] 1 of 1 \u2714
[4e/88f15e] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_INDEX_FOR_ARRIBA (control) [100%] 1 of 1 \u2714
[96/a63807] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA (control)                    [100%] 1 of 1 \u2714
[70/ed269f] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:GET_PATH_ARRIBA_FAIL (getpath)      [100%] 1 of 1 \u2714
[de/c55c2c] process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (control)      [100%] 1 of 1, failed: 1 \u2718
[94/0247f1] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:KALLISTO_QUANT (control)            [100%] 1 of 1 \u2714
[c4/ed347c] process > NFCORE_RNAFUSION:RNAFUSION:PIZZLY_WORKFLOW:PIZZLY (control)                    [100%] 1 of 1 \u2714
[31/313779] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:STAR_FOR_SQUID (control)             [100%] 1 of 1 \u2714
[98/37c4ee] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_VIEW_FOR_SQUID (control)    [100%] 1 of 1 \u2714
[65/933016] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_SORT_FOR_SQUID (control)    [100%] 1 of 1 \u2714
[f2/236cad] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID (squid)                        [  0%] 0 of 1
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE                       -
[a0/da0621] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STAR_FOR_STARFUSION (control)   [100%] 1 of 1 \u2714
[48/25eb97] process > NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION (control)            [100%] 1 of 1 \u2714
[a4/7e45be] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONCATCHER_WORKFLOW:FUSIONCATCHER (control)      [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT                  -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR            -
[ce/bd3c56] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:QUALIMAP_RNASEQ (control)               [100%] 1 of 1 \u2714
[45/b2c955] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:SAMTOOLS_INDEX_FOR_QC (control)         [100%] 1 of 1 \u2714
[fd/6bd94d] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_COLLECTRNASEQMETRICS (control)   [  0%] 0 of 1
[94/d9ba16] process > NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_MARKDUPLICATES (control)         [100%] 1 of 1 \u2714
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:CUSTOM_DUMPSOFTWAREVERSIONS                         -
[-        ] process > NFCORE_RNAFUSION:RNAFUSION:MULTIQC                                             -
-[nf-core/rnafusion] Pipeline completed with errors-
-[nf-core/rnafusion] Pipeline completed with errors-

Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (control)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (control)` terminated with an error exit status (1)

Command executed:

  draw_fusions.R \
      --fusions=control.arriba.fusions.tsv \
      --alignments=control_sorted.bam \
      --output=control.pdf \
      --annotation=Homo_sapiens.GRCh38.102.gtf \
      --cytobands=arriba_v2.3.0/cytobands_hg38_GRCh38_v2.1.0.tsv \
      --proteinDomains=arriba_v2.3.0/protein_domains_hg38_GRCh38_v2.1.0.gff3
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION":
      arriba: $(arriba -h | grep 'Version:' 2>&1 |  sed 's/Version: //')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: Cannot read file: arriba_v2.3.0/cytobands_hg38_GRCh38_v2.1.0.tsv
  Execution halted

Work dir:
  /mnt/dat2/ak/nf/work/de/c55c2cca8749df133f592945784172

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


Why it force to older versions  I mean 2.1.0 instead of 2.3.0 ?
 --cytobands=arriba_v2.3.0/cytobands_hg38_GRCh38_v2.1.0.tsv \
      --proteinDomains=arriba_v2.3.0/protein_domains_hg38_GRCh38_v2.1.0.gff3
Where is the mistake.

Thank you for your time i help
Best wishes
A
