### ISSUE TITLE
References not placed in the correct directory

### ISSUE THREAD

**Issue by jsangalang** [nf-core/rnafusion#336]
### Description of the bug

When running with the option --build-references, the references for some tools were located outside the "references" directory (namely, "arriba", "convert2bed", "gatk4" and "rrna" directories).

After building the references and running the pipeline (indicating the location of the references with the argument --genomes_base ), it did not find certain reference files because it was located outside the "references" directory.
Because of this, there was an error when running arriba for example, since it could not find the blacklist in the "reference" directory.

I fixed this by moving the directories in the "references" directory, but this is a bug when building references.

### Command used and terminal output

```console
nextflow run /mnt/beegfs/userdata/pipelines/nf-core_rnafusion/rnafusion-2.2.0/main.nf --starindex --all --genomes_base /mnt/beegfs/scratch/RNA_Fusion_results/pipeline_results/results_2.2.0/references --input /mnt/beegfs/userdata/pipelines/nf-core_rnafusion/test_sample_plan.csv --outdir /mnt/beegfs/scratch/RNA_Fusion_results/pipeline_results/results_test_2.2.0 --genome GRCh38 -profile singularity --cosmic_username XXXXXXXXX --cosmic_passwd XXXXXXXXX

./results_2.2.0
├── arriba
├── convert2bed
├── gatk4
├── pipeline_info
├── references
    ├── ensembl
    ├── fusion_report_db
    ├── fusioncatcher
    ├── pizzly
    ├── star
    ├── starfusion
└── rrna
```

### System information

Nextflow = 22.10.5
Hardware = HPC
Executor = slurm
Container engine = Singularity version 3.10.5
OS = CentOS Linux
nf-core/rnafusion = 2.2.0

**Comment by mschubert** [comment]
In addition, I'm also getting the following error when running _STAR-Fusion_ on the pre-built references (_nextflow_ 22.10.1, _rnafusion_ 2.2.0, running with singularity):

```
Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION (CF60852)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION (CF60852)` terminated with an error exit status (2)

Command executed:

  STAR-Fusion \
      --genome_lib_dir ctat_genome_lib_build_dir \
      --left_fq file1.fastq.gz --right_fq file2.fastq.gz \
      -J CF60852.Chimeric.out.junction \
      --CPU 16 \
      --examine_coding_effect \
      --output_dir . \


  mv star-fusion.fusion_predictions.tsv CF60852.starfusion.fusion_predictions.tsv
  mv star-fusion.fusion_predictions.abridged.tsv CF60852.starfusion.abridged.tsv
  mv star-fusion.fusion_predictions.abridged.coding_effect.tsv CF60852.starfusion.abridged.coding_effect.tsv

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION"
      STAR-Fusion: $(STAR-Fusion --version 2>&1 | grep -i 'version' | sed 's/STAR-Fusion version: //')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  Error, cannot locate required ctat_genome_lib_build_dir/AnnotFilterRule.pm  ... be sure to use a more modern version
of the companion CTAT_GENOME_LIB  at /usr/local/src/STAR-Fusion/STAR-Fusion line 517.
```

The file _AnnotFilterRule.pm_ is indeed missing in the _references/starfusion/ctat_genome_lib_build_dir_ directory but present _references/starfusion_ directory, so copying it over fixes this issue.

In addition, the following files are missing in the _references/starfusion/ctat_genome_lib_build_dir_ directory but present the build-references _ctat_genome_lib_build_dir_ work directory (producing similar errors):

* AnnotFilterRule.pm
* fusion_annot_lib.idx
* blast_pairs.idx
* trans.blast.align_coords.align_coords.dbm
* ref_annot.gtf
* ref_annot.gtf.mini.sortu

**Comment by rannick** [comment]
convert2bed, rrna and gatk4 contain intermediate files that are not necessary to keep in the references. 
pipeline_info is always generated when running the pipeline
arriba is indeed problematic see fix: https://github.com/nf-core/rnafusion/pull/349

**Comment by mschubert** [comment]
@rannick My issue was indeed fixed with a clean run from the `dev` head, I updated my comment above
