### ISSUE TITLE
Unexpected error using '--cram' option

### ISSUE THREAD

**Issue by grospo** [nf-core/rnafusion#344]
### Description of the bug

When I run the following command:

> nextflow run nf-core/rnafusion -bg -r 2.2.0 -profile myprofile \
>  --outdir /my/outdir \
>  --genomes_base /my/ref/dir \
>  --ensembl_version 102 \
>  --all \
>  --cram arriba,squid,starfusion \
>  --input mysamplesheet.csv

I got the following error:

> [zz/yyzzxx] Submitted process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (xyz)
> WARN: Input tuple does not match input set cardinality declared by process `NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_VIEW_FOR_SQUID_CRAM` -- offending value: [[id:xyz, single_end:false, strandedness:unstranded], /my/dir/xyz.Aligned.sortedByCoord.out.bam]
> [bb/aaccdd] Submitted process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SAMTOOLS_VIEW_FOR_SQUID (xyz)
> Execution aborted due to an unexpected error

I checked that the /my/dir/xyz.Aligned.sortedByCoord.out.bam does exist. Moreover, the pipeline works if I run the exact same command without "--cram arriba,squid,starfusion" option.

### System information

Nextflow  version 22.10.6
Hardware HPC
Executor slurm (same issue using awsbatch)
Version of nf-core/rnafusion 2.2.0

**Comment by rannick** [comment]
https://github.com/nf-core/rnafusion/pull/348
