### ISSUE TITLE
GTF file without "gene_name" attribute column

### ISSUE THREAD

**Issue by grospo** [nf-core/rnafusion#345]
### Description of feature

I run the rnafusion pipeline to build the reference v108. Then I run the fusion calling as follow:

> nextflow run nf-core/rnafusion -bg -r 2.2.0 -profile myprofile
> --outdir /my/outdir
> --genomes_base /my/ref/dir
> --ensembl_version 108
> --all
> --input mysamplesheet.csv

and got the following error:

> [00/aabbcc] Submitted process > NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE (xyz)
> [00/aabbcc] NOTE: Missing output file(s) `*annotated.txt` expected by process `NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE (xyz)` -- Execution is retried (1)
> Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE (xyz)'
> 
> Caused by:
>   Missing output file(s) `*annotated.txt` expected by process `NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE (xyz)`
> 
> Command executed:
> 
>   AnnotateSQUIDOutput.py Homo_sapiens.GRCh38.108.gtf xyz.squid.fusions_sv.txt xyz.squid.fusions.annotated.txt
> 
>   cat <<-END_VERSIONS > versions.yml
>   "NFCORE_RNAFUSION:RNAFUSION:SQUID_WORKFLOW:SQUID_ANNOTATE":
>       squid: $(echo $(squid --version 2>&1) | sed 's/v//')
>   END_VERSIONS
> 
> Command exit status:
>   0
> 
> Command output:
>   GTF file attribute column doesn't contain gene_name: 1        havana  transcript      2581560 2584533 .       +       .       gene_id "ENSG00000228037"; gene_version "1"; transcript_id "ENST00000424215"; transcript_version "1"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; tag "basic"; tag "Ensembl_canonical"; transcript_support_level "5";
> 
> Work dir:
>   /my/working/dir
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
> 
> 
> Execution cancelled -- Finishing pending tasks before exit

I checked that ensembl v108 GTF file contains entries without "gene_name" attribute. I also verified that this is not the case with ensembl v102 GTF file (all entries contain "gene_name" attribute), and - in fact - I haven't encountered any errors when running the same command using v102 reference files and with "--ensembl_version 102" option.
I was wondering if this issue should be fixed at GTF level - that means removing from GTF file entries without "gene_name" attribute - or whether this could be fixed at rnafusion pipeline level.

**Comment by rannick** [comment]
Unfortunately this should be fixed at the squid level

**Comment by rannick** [comment]
The reasoning is the following: squid has not been updated since 5 years, instead of investing resources into formatting gtf files for squid, I think it would make more sense to replace squid with other more up-to-speed fusion detection tools such as MANTA (https://github.com/Illumina/manta/blob/master/docs/userGuide/README.md#rna-seq)

**Comment by rannick** [comment]
https://github.com/nf-core/rnafusion/pull/347
