### ISSUE TITLE
Ericscript omission in pipeline workflow

### ISSUE THREAD

**Issue by jsangalang** [nf-core/rnafusion#363]
### Description of feature

Hello, I was just wondering why Ericscript has been removed in the current pipeline workflow? As I've seen before, it was included in the previous iterations (ex., v.1.2.0), but not in the recent versions (ex. v.2.2.0). I've been looking, but I didn't see any answers to this. Thanks!

**Comment by rannick** [comment]
It is no longer possible to run as the references are broken and not up to date. EricScript is not functional anymore.
