### ISSUE TITLE
Megafusion VCF: FOUND_DB and tools are often "nan"

### ISSUE THREAD

**Issue by mschubert** [nf-core/rnafusion#367]
### Description of the bug

Using _rnafusion_ `2.3.4`, _megafusion_ produces produces lines as expected

```
10  133402xxx   .   N   N[10:133456xxx[ .   PASS    SVTYPE=BND;CHRA=10;CHRB=10;GENEA=MTG1;GENEB=SCART1;ORIENTATION=+,+;FOUND_DB=[];ARRIBA=false;FUSIONCATCHER=true;PIZZLY=true;SQUID=false;STARFUSION=false;TOOL_HITS=2.0;SCORE=0.125   GT:DV:RV:FFPM   ./1:5:3:0.1815
```

but more often than not, `FOUND_DB` and the tools are reported incorrectly (`nan` instead of `true`/`false` whether a tool has found it)

```
3   96618xxx    .   N   N]7:94394xxx]   .   PASS    SVTYPE=BND;CHRA=3;CHRB=7;GENEA=MTRNR2L12;GENEB=COL1A2;ORIENTATION=-,+;FOUND_DB=nan;ARRIBA=nan;FUSIONCATCHER=nan;PIZZLY=nan;SQUID=nan;STARFUSION=nan;TOOL_HITS=nan;SCORE=nan GT:DV:RV:FFPM   ./1:0:7:5899
```

For my file for instance, there are 42 `nan` lines and 10 non-`nan` lines.

The `nan` lines largely overlap with fusions not present in _fusionreport_ due to the minimum of 2 tools filter, but not completely

### Command used and terminal output

```console
Off-the-mill run, pipeline completed successfully
```

**Comment by rannick** [comment]
Ok so this is due to the default values of 
```
fusionreport_filter = true
fusioninspector_filter = false
```
fusionreport index, used in MEGAFUSION is filtered by default, but if fusioninpector considers also non-filtered fusions, the information from fusionreport index are not available. 
Proposed fix: remove the above options in favor of a tools_cutoff (default = 1) used for both fusionreport and fusioninspector (https://github.com/nf-core/rnafusion/issues/354)

**Comment by rannick** [comment]
`fusionreport_filter = true` is designed to avoid index files of several gigabytes when pizzly is used

**Comment by rannick** [comment]
There is an explanation for the extra nan you might encounter. FusionInspector inspects each gene further than just the gene pair fed in from fusion-report and sometimes add another gene pair to consider. As those are not found by tools, the values are "nan". This is not a code issue but a documentation of the effect is necessary. Added to https://github.com/nf-core/rnafusion/issues/368

**Comment by rannick** [comment]
As the fix involves a argument change, it will only be merged in 3.0.0, in the meantime it is recommended to use: ```
```
fusionreport_filter = true 
fusioninspector_filter = true
```
or 
```
fusionreport_filter = false
fusioninspector_filter = false
```

**Comment by rannick** [comment]
https://github.com/nf-core/rnafusion/pull/389

**Comment by rannick** [comment]
Merged, closing
