### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fevac** [nf-core/rnafusion#368]
### Description of feature

Improve and update official documentation. In particular:
- General review and update
- Add `directory structure` section (like https://nf-co.re/sarek/3.2.2/output#directory-structure)
- Update and improve output files description to help interpretation.  Make clear which filtering is performed where (e.g. FusionInspector)
- Add the default options for each tool
For inspiration:
- https://nf-co.re/rnaseq/ 
- https://nf-co.re/sarek

**Comment by rannick** [comment]
Make clear magafusion output and arriba visualisation are from results of fusioninspector (filtered)

**Comment by rannick** [comment]
Closed in https://github.com/nf-core/rnafusion/pull/396
