### ISSUE TITLE
Support other cloud platform providers other than s3 or local

### ISSUE THREAD

**Issue by sclan** [nf-core/rnafusion#374]
### Description of feature

The s3 check prevents any other cloud platform from running the pipeline with the following if statement
https://github.com/nf-core/rnafusion/blob/master/workflows/rnafusion.nf#L36

Aside from s3:// there are also other platform syntax such as gs://

**Comment by rannick** [comment]
@sclan any other wishes than gs?

**Comment by efgstone** [comment]
I'm using dx://. I have created a pull request for a fix for this: https://github.com/nf-core/rnafusion/pull/383
