### ISSUE TITLE
Not a valid path value type: java.util.LinkedHashMap ([id:Homo_sapiens.GRCh38.102.chr.gtf])

### ISSUE THREAD

**Issue by maressyl** [nf-core/rnafusion#415]
### Description of the bug

I get an error in StringTie I'm not sure to understand about a file that seems to exist in my reference build :
`build/references/ensembl/Homo_sapiens.GRCh38.102.chr.gtf`

I had the problem during my first tests with the `dev` branch so I switched to the 2.3.4 release, but now it seems the error made its way to 2.4.0. I am using the last "edge" Nextflow version as I encountered problems with the 23.04.X version (#411).

I built the references in two steps as we discussed previously to avoid a problem with our proxy, on a first server with `-build --pizzly --starfusion --fusioncatcher --arriba --build_references` and on another with `build --fusionreport --build_references`, perhaps I missed to build something ?

### Command used and terminal output

```bash
./nextflow-23.09.2-edge-all -c HCL.conf run maressyl/rnafusion -r 2.4.0-HCL \
    --all \
    --input input/22288/samplesheet.csv \
    --outdir output/22288 \
    -profile singularity \
    --genomes_base "/srv/scratch/rnafusion-2.4.0/build/references" \
    --read_length 150 \
    -ansi-log false \
    -w ./work \
    -with-tower \
    -resume
```
```
ERROR ~ Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:STRINGTIE_WORKFLOW:STRINGTIE_STRINGTIE (1)'

Caused by:
  Not a valid path value type: java.util.LinkedHashMap ([id:Homo_sapiens.GRCh38.102.chr.gtf])
```

### Relevant files

`HCL.conf`

```
singularity.envWhitelist = "http_proxy,https_proxy"

tower {
  enabled = true
  accessToken = 'REDACTED'
  workspaceId = 'REDACTED'
}
```

### System information

- Nextflow 23.04.4-all ([as used in CI](https://github.com/nf-core/rnafusion/blob/dev/.github/workflows/ci.yml#L27))
- HPC
- local executor
- singularity-ce version 3.8.0
- Debian 11
- nf-core/rnafusion 2.4.0 [with a minor tweak](https://github.com/maressyl/rnafusion/tree/2.4.0-HCL)

**Comment by rannick** [comment]
There is a problem with the channel i/o, will solve with https://github.com/nf-core/rnafusion/pull/416
