### ISSUE TITLE
fails at fusion inspector  

### ISSUE THREAD

**Issue by visbal-ki** [nf-core/rnafusion#418]
### Description of the bug

Hey, I am running nf-core/rnafusion pipeline on grch37 reference genome and I encountered a bug whilst in the fusion inspector step. 

log:

Oct-04 20:49:49.064 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
task: name=NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (RNA-T-K4535-22); work-dir=/nfs/TEST/work/6b/0d68abd9f35df57bf311a045a146ff
error [nextflow.exception.ProcessFailedException]: Process NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (RNA-T-K4535-22) terminated with an error exit status (1)
Oct-04 20:49:50.197 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (RNA-T-K4535-22)'

Caused by:
Process NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (RNA-T-K4535-22) terminated with an error exit status (1)

Command executed:

FusionInspector
--fusions RNA-T-K4535-22.fusionreport.tsv
--genome_lib ctat_genome_lib_build_dir
--left_fq RNA-T-K4535-22_1.merged.fastq.gz --right_fq RNA-T-K4535-22_2.merged.fastq.gz
--CPU 12
-O .
--out_prefix RNA-T-K4535-22
--vis

cat <<-END_VERSIONS > versions.yml
"NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR":
STAR-Fusion: $(STAR-Fusion --version 2>&1 | grep -i 'version' | sed 's/STAR-Fusion version: //')
END_VERSIONS

Command exit status:
1

Command output:
Execution Time = 0.07 minutes. CMD: cp RNA-T-K4535-22.fa fi_workdir/RNA-T-K4535-22.fa
Running: touch chckpts_dir/cp_contigs_file_workdir
Running: cp RNA-T-K4535-22.gtf fi_workdir/RNA-T-K4535-22.gtf
Execution Time = 0.27 minutes. CMD: cp RNA-T-K4535-22.gtf

...

Error: Command '/usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/RNA-T-K4535-22.fa --max_mate_dist 100000 -G fi_workdir/RNA-T-K4535-22.gtf --CPU 12 --out_prefix RNA-T-K4535-22.star --ou>
Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/RNA-T-K4535-22.fa --max_mate_dist 100000 -G fi_workdir/RNA-T-K4535-22.gtf --CPU 12 --out_prefix RNA-T-K4535-22.star -->
st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:788
st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942

**there was also another error near the bottom of the log** 

WARNING, no gtf annotations found for [CT867976.1]
Done.
-parsing GTF file: RNA-T-K4535-22.gtf

Running CMD: /usr/local/bin/STAR --runThreadN 12 --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx --outSAMtype BAM SortedByCoordinate --twopassMode None --alignSJDBoverhangMin 10 -->
EXITING because of FATAL ERROR: cannot insert sequence on the fly because of strand GstrandBit problem
SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

Oct 04 20:49:23 ...... FATAL ERROR, exiting
Error, cmd: /usr/local/bin/STAR --runThreadN 12 --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx --outSAMtype BAM SortedByCoordinate --twopassMode None --alignSJDBoverhangMin 10 --gen>
Pipeliner::run(Pipeliner=HASH(0x55eddbfec4a0)) called at /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl line 322
Traceback (most recent call last):
File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1942, in
FusionInspector().run()
File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1516, in run
pipeliner.run()
File "/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py", line 71, in run
cmd.run(checkpoint_dir)
File "/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py", line 132, in run
raise RuntimeError(errmsg)
RuntimeError: Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/RNA-T-K4535-22.fa --max_mate_dist 1000>
st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:788
st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942
]

**Comment by rannick** [comment]
> Running CMD: /usr/local/bin/STAR --runThreadN 12 --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx --outSAMtype BAM SortedByCoordinate --twopassMode None --alignSJDBoverhangMin 10 --> EXITING because of FATAL ERROR: cannot insert sequence on the fly because of strand GstrandBit problem SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

This is an error that commonly arises with STAR, you should try your luck on the forum for solutions. But it is not a rnafusion issue so I will close this from here

**Comment by rannick** [comment]
Also created this: https://github.com/nf-core/rnafusion/issues/422
