### ISSUE TITLE
Ensembl version is not supported by squid and fusion catcher doesn't update its directory name /fusioncatcher/human_v*ensembl* 

### ISSUE THREAD

**Issue by ZheFrench** [nf-core/rnafusion#421]
### Description of the bug

I'm trying to run rnafusion and I wanted to change the ensembl reference version for the  --build_references .
I clone the nf-core/rnafusion
I changed nextflow.config for all stuffs relative to ensembl. Actual version setting for ensembl is 102, and I want to use the 109. I also tried by passing as parameter --ensembl_version 109.
Finaly I get "Ensembl version is not supported by squid".

### Command used and terminal output

```console
nextflow clone nf-core/rnafusion 

nextflow run rnafusion  -profile test  --build_references --ensembl_version 109 --all --cosmic_username XXX --cosmic_passwd XXX --genomes_base /data/ --outdir /pathTo/fusion -stub
```

### Relevant files

[nextflow.log.gz](https://github.com/nf-core/rnafusion/files/13031473/nextflow.log.gz)

### System information

N E X T F L O W  ~  version 23.10.0
 nf-core/rnafusion  2.4.0
Ubuntu 18.04
Hardware HPC without job scheduler
local
Singularity

**Comment by rannick** [comment]
Indeed, as you noticed, other ensembl versions are not compatible with squid and `--all` includes squid. Squid will be removed from future version so I will not improve documentation on this. Can be closed with the next release

**Comment by ZheFrench** [comment]
I found a similar bug with fusioncatcher which will create a directory called human_v102  even if you change `fusioncatcher_ref` in netflow.config to `human_v109`
`    fusioncatcher_ref             = "${params.genomes_base}/fusioncatcher/human_v109"`

build_references will works but then it complains when you try to execute the pipeline to detect fusion.

**Comment by rannick** [comment]
Unfortunatly, the references for fusioncatcher only exist for ensembl 102: https://sourceforge.net/projects/fusioncatcher/files/data/ 
This is why human_v102 is created. That will not be influenced by the `ensembl_version` parameter
