### ISSUE TITLE
URGENT: pin nf-validation version

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/rnafusion#471]
### Description of the bug

To prevent breaking this pipeline in the near future, the nf-validation version should be pinned to version 1.1.3 like:

```
plugins {
    id 'nf-validation@1.1.3'
}
```

**Comment by rannick** [comment]
Already in dev: https://github.com/nf-core/rnafusion/blob/abcc7a88315b15848439fa3af62273b3959816b8/nextflow.config#L253, will be in the next release

**Comment by nvnieuwk** [comment]
Thank you! Any idea when this new version will be released? :)

**Comment by rannick** [comment]
Well, thank you for making sure it will be in the next version :) 
I am working part-time until the beginning of April, making everything slower. The plan is to release a patch asap and a more thorough  update end of April/beginning of May

**Comment by nvnieuwk** [comment]
Awesome! A patch would be perfect :partying_face:
