### ISSUE TITLE
Arriba download -- proxy issues

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rnafusion#495]
### Description of the bug

could be solved via `--no-check-certificate` option being added to wget. 

### Command used and terminal output

```console
Standard run to build reference index
```

**Comment by apeltzer** [comment]
https://github.com/nf-core/rnafusion/pull/496

**Comment by apeltzer** [comment]
More accurately, the problem is when you're behind a proxy and that interferes with SSL certificates in the chain. WGET then will not do the download, your jobs when building the DB will fail. 

Attached PR #496  fixes / addresses this.

**Comment by rannick** [comment]
Solved locally and on nf-core/modules with https://github.com/nf-core/modules/pull/6765
