### ISSUE TITLE
File extensions should be more flexible

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rnafusion#500]
### Description of the bug

Copying in a request from @OlgaChern via Slack

----- 
Hi there! A small, but potentially useful change in regards to files handling. From one of our external collaborators we are getting files with names ending with "_fastq.gz" extensions, which in the end leads to the error (see below). Since the number of files is extensive the work around was ingesting the pipeline and commenting the check for file extensions, instead of using the nfcore version directly. It would be cool to be a bit more general with names to allow flexibility. Maybe something to consider for the next releases. Thank you in advance!

```
Command error:
[CRITICAL] The FASTQ file has an unrecognized extension: s3://PATH_TO_FILE/file_fastq.gz It should be one of: .fq.gz, .fastq.gz On line 2.
```

**Comment by rannick** [comment]
Implemented
