### ISSUE TITLE
Create nf-tests for "hgnc" module

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/rnafusion#524]
### Description of feature

Create nf-tests for "hgnc" module

**Comment by atrigila** [comment]
I am working on the nf-tests for these local modules. The file `hgnc_complete_set.txt` seems to no longer be available at the original FTP link from the EBI. When attempting to download it using wget (`wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt`), the request fails. 

cc @apeltzer @grst @rannick

**Comment by apeltzer** [comment]
This is now on google storage apis - see https://www.genenames.org/download/archive/#!/#tocAnchor-1-2 :)

**Comment by apeltzer** [comment]
If we always take the latest release, the url would be `https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt`

**Comment by atrigila** [comment]
thank you! :)

**Comment by atrigila** [comment]
Closed via #540
