### ISSUE TITLE
Create nf-tests for "arriba_workflow" subworkflow

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/rnafusion#530]
### Description of feature

Create nf-tests for "arriba_workflow" subworkflow

**Comment by atrigila** [comment]
This module is already part of nf-core and has been migrated into the pipeline.

**Comment by nschcolnicov** [comment]
This is for the subworkflow https://github.com/nf-core/rnafusion/blob/dev/subworkflows/local/arriba_workflow.nf
