### ISSUE TITLE
new module: CTAT/SPLICING

### ISSUE THREAD

**Issue by matthdsm** [nf-core/rnafusion#538]
### Description of feature

Hi!

We'd like to add a [new module](https://github.com/nf-core/modules/issues/7057) to rnafusion.
Would you be open to that? We'll do the heavy lifting, we just need an approval to push upstream once it's done.

Cheers
Matthias

**Comment by rannick** [comment]
Yes that sounds great!

**Comment by rannick** [comment]
https://github.com/nf-core/rnafusion/pull/587
