### ISSUE TITLE
Batch mode

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#54]
Be able to run multiple sets of files.

**Comment by apeltzer** [comment]
Yes please :-)

**Comment by matq007** [comment]
If samples ran in batch mode, create one more file which would contain summary of all fusions from all samples as shown in the example below:

```
# fusions_summary.json
[
  "sample1": [fusions: "BCR-ABL1": {"score": 1, "databases": "X, Y, Z"} ... ]
  "sample2": [fusions: "BCR-ABL1": {"score": 1, "databases": "X, Y, Z"} ... ]
  ..
]
```

**Comment by matq007** [comment]
x-ref: https://github.com/nf-core/rnafusion/issues/18

**Comment by ChiBia** [comment]
Hello,
have you got any idea about the timeline for batch mode implementation?

**Comment by matq007** [comment]
> Hello,
> have you got any idea about the timeline for batch mode implementation?

Probably sometime around June. I am trying to write updates on Slack channel regarding the progress.

**Comment by marchoeppner** [comment]
Just bumping, this seems to have been cooking for a while. The latest dev branch seems non-functional, although some of the suggested changes appear present. Any eta?

**Comment by matq007** [comment]
Hey @marchoeppner, trying to deal with with it for the last few weeks. If you just run the fusion tools with `--debug`, the pipeline is able to run on multiple samples. @MaxUlysse is helping me out with integrating the fusion results with `fusion-report`. I want to close this issue until end of the year.

**Comment by marchoeppner** [comment]
Hi, just checking in to see if there is a new ETA? We'll have to analyse > 200 RNA fusion samples within the next couple of weeks, would be very useful to have a production-ready batch mode for that ;)

**Comment by matq007** [comment]
Hey @marchoeppner, I have just asked @MaxUlysse for a help so we will update the status at the end of the week :)

**Comment by matq007** [comment]
Solved by @MaxUlysse, working version on `dev` branch.
