### ISSUE TITLE
Error in `BUILD_REFERENCES`, `params.no_cosmic` not handled for some tools

### ISSUE THREAD

**Issue by atrigila** [nf-core/rnafusion#557]
### Description of the bug

When running the  pipeline with the `--no_cosmic` parameter, the `FUSIONREPORT_DOWNLOAD` is executed. This makes the pipeline fail as  `params.cosmic_username` and `params.cosmic_passwd` are not provided.

**Error**:
```
ERROR ~ A process input channel evaluates to null -- Invalid declaration `val username`
```

**Cause**:
In `BUILD_REFERENCES`, the following line does not account for the `params.no_cosmic` :
```
if (params.fusionreport || params.all) {
    FUSIONREPORT_DOWNLOAD(params.cosmic_username, params.cosmic_passwd)
}
```

### Command used and terminal output

```console
nextflow run nf-core/rnafusion -r dev \
  --build_references --all \
  --no_cosmic \
  --outdir build_references \
  -profile docker
```

**Comment by rannick** [comment]
#558 does not take into account that there are 2 other databases that need to be downloaded from FUSIONREPORT_DOWNLOAD @atrigila
