### ISSUE TITLE
Doc improvement

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#58]
It looks like the documentation is not clear enough and maybe too complicated to follow. Should be more clear so here are some suggestions so far:
- [x] Fix link on `README.md` 
- [ ] Small video tutorial how to run the pipeline together with downloading the references

Any other suggestions are more than welcome 😺

**Comment by ewels** [comment]
* [ ] Example HTML reports to view online

**Comment by matq007** [comment]
Changes implemented in #61

**Comment by matq007** [comment]
Done: https://github.com/matq007/fusion-report/commit/ffcf5ea28ef614ecdbd2becd80f0dbd6ab347a86
