### ISSUE TITLE
Tool results are overwritten for each sample

### ISSUE THREAD

**Issue by mtstahl** [nf-core/rnafusion#59]
Each tool is storing sample-specific fusions according to the pattern `publishDir "${params.outdir}/tools/StarFusion", mode: 'copy'`. However, the files are overwritten for each sample.

**Comment by mtstahl** [comment]
I propose changing the above code pattern to `publishDir "${params.outdir}/tools/StarFusion/${name}", mode: 'copy'`.

**Comment by matq007** [comment]
Hey Matias, currently the pipeline supports only one single/paired-end input. The new version will have a batch mode. In the meantime I would suggest using `outdir` for each new run.

**Comment by mtstahl** [comment]
Now, I see what #54 is. 😀
