### ISSUE TITLE
Look into MultiQC report

### ISSUE THREAD

**Issue by ewels** [nf-core/rnafusion#6]
_From @ewels on March 13, 2018 10:49_

Check what the MultiQC report looks like currently and write new MultiQC modules for missing tools as required.

Add in config file, tweaks for pipeline (eg. comment saying what generated it) and software version reporting.

_Copied from original issue: SciLifeLab/NGI-RNAfusion#10_

**Comment by matq007** [comment]
For now, we are using a custom tool that is triggered in the pipeline to generate a section in MultiQC report. We are generating a bar graph, meaning: number of counted fusion genes per tool + intersect of all of them.

**Comment by matq007** [comment]
No further changes required, closing.
