### ISSUE TITLE
Implement scoring

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#62]
It would be a good idea to implement some sort of scoring function for each tool individually as each tool uses a slightly different approach for fusion detection.

- [ ] STAR-Fusion
- [ ] Ericscript (own score)
- [ ] Fusioncatcher
- [ ] Pizzly
- [ ] Squid

Could clustering be an option here?
This issue is used for discussions and suggestions.

**Comment by apeltzer** [comment]
Some weighted voting system maybe? I guess all tools have pretty different benchmarking results, so could be weighted accordingly based on real-world tests... 

e.g. benchmark on some datasets and then justify using the ones with highest SE and SP giving them most weight.

**Comment by matq007** [comment]
Closing and moving the issue to a new repository where the discussion can continue: https://github.com/matq007/fusion-report/issues/2. 
I've implemented a basic scoring function, we will see what will be the feedback.
