### ISSUE TITLE
Failed to create Conda environment

### ISSUE THREAD

**Issue by gybeata** [nf-core/rnafusion#66]
Hi,
I keep getting an error related to conda environment:

```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'build_star_index (genome.fa)'

Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /network/lustre/dtlake01/bioinfo/processed_data/2019/PB19_JLE_RSQ/TGNR/FusionGenes/rnafusion/work/conda/nf-core-rnafusion-1.0-b23b472a3dccdeebb3cc3605e2f80213 --file /network/lustre/dtlake01/bioinfo/s
upport_data/TOOLS/nextflow/nf-core/rnafusion-master/environment.yml
  status : 143
  message:
    ==> WARNING: A newer version of conda exists. <==
      current version: 4.5.12
      latest version: 4.6.9
    
    Please update conda by running
    
        $ conda update -n base -c defaults conda
```

Can you suggest how to get around this error?

Another question:  I would need to run the pipeline on a machine without internet access. Is there any way to do that? For example if I build the conda environment aforehad in the working directory? 

Thank you

**Comment by matq007** [comment]
Hi!

It looks like you are trying to run the pipeline offline without downloading the images beforehand. Are you going to run the images with Singularity/Docker? 
For Singularity I have prepared a helper script here: https://github.com/nf-core/rnafusion/blob/master/utils/download-singularity-img.sh

**Comment by matq007** [comment]
Closing the issue, related to the server configuration. Can't do much about it.
