### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by xiucz** [nf-core/rnafusion#76]
Hi, 
In the installation part, 

https://github.com/nf-core/rnafusion/blob/master/docs/installation.md

** 3.2) Software deps: conda **
> then follow the same pattern as above and use the flag -profile conda

Please write it more clearly.
Thank you.

**Comment by matq007** [comment]
The documentation has been updated a little. In case of `conda`, you just have to run the pipeline with `-profile conda`.
