### ISSUE TITLE
hg19/GRCh37 references

### ISSUE THREAD

**Issue by ahwanpandey** [nf-core/rnafusion#77]
Hello,

Is there an example to download hg19/GRCh37 references anywhere, like the link you guys have for GRCh38?

https://github.com/nf-core/rnafusion/blob/master/docs/references.md

Thanks!

**Comment by matq007** [comment]
Hi,

no at the moment, we support now only GRCh38. If you would like to use a different genome version you would have to build a reference for each fusion tool individually:

1. STAR-Fusion (build a reference similar to [this](https://github.com/nf-core/rnafusion/blob/master/docs/references.md#star-fusion-custom-ensembl-example))
2. FusionCatcher (a lot of references)
3. Squid (requires STAR-Index)
4. EricScript (download this [reference](https://drive.google.com/file/d/0B9s__vuJPvIibDRIb0RFdHFlQmM/view?usp=sharing))
5. Pizzly (custom FASTA and GTF)

We might support this in future but not at the moment.

**Comment by brucemoran** [comment]
Hi all,

I have completed implementation of GRCh37 references, and their use, for all but FusionCatcher. 

Would you accept a pull request without it?

From an [issue on FusionCatcher github](https://github.com/ndaniel/fusioncatcher/issues/91) it looks like we would need an install of v0.99.3a which is unsupported.

I am happy to continue using [my fork](https://github.com/brucemoran/rnafusion/tree/GRCh37), if you want I am also happy to make a pull request (warning: I have no experience with that!).

Thanks,

Bruce.

**Comment by MaxUlysse** [comment]
Hi Bruce,

We do welcome pull request.
Read the issue regarding FusionCatcher, and I think we can do without it as long as we warn people properly.
If you need any help making the PR, don't hesitate to ask ;-)
We do have a small guide here: [CONTRIBUTING.md](https://github.com/nf-core/rnafusion/blob/master/.github/CONTRIBUTING.md).
If you feel like there is some information missing, please do tell.

All the best,
Maxime
