### ISSUE TITLE
summary report

### ISSUE THREAD

**Issue by PeterBailey** [nf-core/rnafusion#80]
Further to previous issues with permissions:

This was fixed by setting fixOwnership = true

Running the pipeline now results in the following error - see below.

running .command.sh with fusion_report installed locally finishes without error

Caused by:
  Process `summary (PM1)` terminated with an error exit status (1)

Command executed:

  fusion_report run PM1 . /home/pbailey/rnafusion_references/databases/ \
      --starfusion star-fusion.fusion_predictions.tsv --pizzly pizzly_fusions.txt --squid fusions_annotated.txt

Command exit status:
  1

Command output:
  Skipping ericscript, due to missing None
  Skipping fusioncatcher, due to missing None

Command error:
  Defined path doesn't exist

Work dir:
  /media/pbailey/local_data/SCC_fastqs_CL/work/6b/a2627517bf35470f63eab710c37b66

**Comment by PeterBailey** [comment]
Also permissions of *db files correct

**Comment by matq007** [comment]
Hi Peter, the error yields when database path has wrong permissions. What about the permissions of the folder itself `ls -laF /home/pbailey/rnafusion_references/databases`? Are you running the pipeline with Docker?

**Comment by PeterBailey** [comment]
Hi Martin, yes running in Docker. Permissions on the reference folders are pbailey:pbailey and not root.

**Comment by matq007** [comment]
I'm not sure it is necessary to run with `fixOwnership = true`. We have observed similar behavior [here](https://github.com/nf-core/rnafusion/issues/75#issuecomment-486890415) and it got resolved by running the pipeline without that setting

**Comment by PeterBailey** [comment]
Yes, this was required due to Docker setting output files as root:root!

I can run:

fusion_report run PM1 . /home/pbailey/rnafusion_references/databases/ 
--starfusion star-fusion.fusion_predictions.tsv --pizzly pizzly_fusions.txt --squid fusions_annotated.txt

locally via .command.sh but not through docker? would changing the runOptions flag be a better or option?

**Comment by matq007** [comment]
Ah, ok!
I am not really sure, you could try without `fixOwnership = true` and maybe setting the `runOptions`. I haven't tested the pipeline on Mac, because I usually test all the tools which require much more horsepower than my bad boy has. It might require some other weird flags in the configuration. 
If it doesn't help, worst case scenario, you can install the `fusion-report` manually with `conda install -c bioconda fusion-report` and execute it with:
```bash
fusion_report run "PM1" . /home/pbailey/rnafusion_references/databases/ 
--starfusion star-fusion.fusion_predictions.tsv --pizzly pizzly_fusions.txt --squid fusions_annotated.txt
```

**Comment by PeterBailey** [comment]
Run on linux -

**Comment by PeterBailey** [comment]
Will run fusion_report separately after pipeline fail - thanks
