### ISSUE TITLE
Embarassing typo

### ISSUE THREAD

**Issue by afonsoguerra** [nf-core/rnafusion#82]
Hi all,

There seems to be a typo, either in the report generation script or in the underlying databases whereby frame-shifts read frame-$#!t this when getting results from ChiTaRS3.1 in the detailed tables. 

Best wishes,
Afonso

**Comment by matq007** [comment]
Ah, thank you for the catch. This is unfortunately in a FusionGDB. I will update the download script. Moving the issue to `fusion-report`.
