### ISSUE TITLE
Add fusion-report to list of tools in readme

### ISSUE THREAD

**Issue by ewels** [nf-core/rnafusion#84]
**fusion-report** is one of the major tools that is run in this pipeline now, so I think it would be appropriate to have in the summary table at the top of the readme.. What do you think? If not in the table, then it would be good to at least mention it in the text underneath.

Also where it is mentioned at the bottom, it would be good to remove the version number as this will get out of date easily. Plus it would be good to have the full GitHub link to matq007/fusion-report, instead of just the text.

**Comment by matq007** [comment]
Sounds good, I totally forgot to add it there 😱.
