### ISSUE TITLE
Feature request: Addition of arriba fusion caller

### ISSUE THREAD

**Issue by leiendeckerlu** [nf-core/rnafusion#88]
Hi there,

I was wondering if there are any plans to include the arriba fusion caller in a future version of the rnafusion pipeline?

[https://arriba.readthedocs.io/en/latest/](https://arriba.readthedocs.io/en/latest/)

Thank you,

Lukas

**Comment by matq007** [comment]
Hi @leiendeckerlu, yes. I think I've already implemented it in the `dev` branch. I will try to push a new release ASAP. I've been working on new version of fusion-report until now.

**Comment by leiendeckerlu** [comment]
Excellent news - thanks for letting me know!
