### ISSUE TITLE
Pipeline not running on multiple samples

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/rnafusion#90]
Hi,

so the pipeline in its current state won't run on multiple samples since all the "reference" inputs are single emissions that apparently force the respective processes to only consider the first read input (1 reference <-> many samples). 

This should be fixed by adding a ".collect()" to the various single-emission channels (e.g. the references). 

/M

**Comment by matq007** [comment]
Hi @marchoeppner, yes that is correct. I have the batch mode as high priority. The problem is I haven't tested it yet. I am not sure how it will act if multiple stuff are executed in parallel as the pipeline is quite computationally hungry.

**Comment by matq007** [comment]
x-ref: https://github.com/nf-core/rnafusion/issues/54
