### ISSUE TITLE
iGenomes currently not optional, but deactivated by default

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/rnafusion#91]
Currently, the pipeline deactivates iGenomes by default; but it expects the "params.genomes" to be set, for example here:

https://github.com/nf-core/rnafusion/blob/d4a622c2e24148c568994f3d019b2a3b5a014e17/main.nf#L87

I suppose this should be put into a condition , to also allow setting params.fasta and params.gtf from outside the pipeline.

**Comment by matq007** [comment]
Ah, you are right! Good point, I will fix this in next version. Thank you for the catch 👍

**Comment by matq007** [comment]
Solved. The upcoming version will only support Ensembl version as was discussed on Slack channel.
