### ISSUE TITLE
_starGenome error in StarFusion

### ISSUE THREAD

**Issue by baileyglen** [nf-core/rnafusion#93]
First time user of nextflow here, so forgive me if this is a basic mistake.
Should sudo be required to run rnafusion?
I am attempting to run RNAfusion for the first time, with the only caller being StarFusion. I am getting the following error, but if I run with sudo I get past the error.

```
Error executing process > 'star_fusion (HS_P53_RNA_7_21_14_S17_test_L006_R)'
Caused by:

  /home/dac233/work/52/7810ddcdf8f17bd4cc9560de352e21/_STARgenome
```
Should sudo be required? I notice that this directory has 700 for permissions, which is what led me to try sudo in the first place.

**Comment by matq007** [comment]
Hi @baileyglen the permissions depend on the system you are using. Could you first provide the whole output (`nextflow.log`)?

**Comment by matq007** [comment]
Closing due to no follow-up.
