### ISSUE TITLE
Pipeline stops if EricScript doesn't find any fusion

### ISSUE THREAD

**Issue by ChiBia** [nf-core/rnafusion#94]
Hi,
the pipeline prematurely stops throwing the message error that you can find below when EricScript doesn't find any fusions.
If EricScript correctly complete its job without finding any fusion it writes the file 'fusions.results.total.tsv' with the line 'No chimeric transcripts found!' but doesn't generate the file 'fusions.results.filtered.tsv'. 
The missing ‘filtered.tsv’ stops the pipeline.
 

Sep-04 12:53:10.711 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'ericscript (ARA_260006_10_01_GCCAAT_L002)'

Caused by:
  Missing output file(s) `./tmp/fusions.results.filtered.tsv` expected by process `ericscript (ARA_260006_10_01_GCCAAT_L002)`

Command executed:

  ericscript.pl \
      -db ericscript_db_homosapiens_ensembl84 \
      -name fusions \
      -p 16 \
      -o ./tmp \
      ARA_260006_10_01_GCCAAT_L002_R1_001.fastq.gz \
      ARA_260006_10_01_GCCAAT_L002_R2_001.fastq.gz

Command exit status:
  0

Command output:
  
  [EricScript] Starting EricScript analysis for sample fusions.
  [EricScript] Aligning with bwa ...done. 
  [EricScript] Extracting discordant alignments ... done. 
  [EricScript] Building exon junction reference ... done. 
  [EricScript] Aligning to exon junction reference ... done. 
  [EricScript] Recalibrating junctions ... done. 
  [EricScript] Aligning to recalibrated junction reference ... done. 
  [EricScript] Scoring candidate fusions ...done. 
  [EricScript] No chimeric transcripts found! Writing results ...done. 

Command error:
  Error: No chimeric transcripts found. Exit!
  Execution halted

**Comment by MaxUlysse** [comment]
Hi,
Thanks a lot for this issue.
Can you tell which version of rnafusion you were using?
I do believe that this was fixed on the `dev` branch.
All the best,
Maxime

**Comment by ChiBia** [comment]
yep, it's version 1.0.2 (singularity image)

**Comment by matq007** [comment]
It is weird @MaxUlysse. All fusion tool outputs are set as optionals (https://github.com/nf-core/rnafusion/blob/d4a622c2e24148c568994f3d019b2a3b5a014e17/main.nf#L421).

**Comment by ChiBia** [comment]
I've checked my main.nf, as a matter of fact it's not set as optional in my copy, I first installed v1.0.1 and must have messed something when updating. thanks for the help

418     output:
419     file './tmp/fusions.results.filtered.tsv' into ericscript_fusions
