### ISSUE TITLE
fusioncatcher references version

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#95]
Hello,

I am trying the pipeline and I ran into a little problem that prevents the use of fusioncatcher.

In the [script](https://github.com/nf-core/rnafusion/blob/master/download-references.nf#L155-L160) the references are outdated. 

So I locally modified it to download the v98 (the currently available one).

However, it does not work when the pipeline is launched. 

Maybe due to what is bundled in the singularity image, this is the exit message from Nextflow execution:

```
  ....................
  ERROR: The version of the data build does not match the version of this pipeline!
  Please, run again the 'fusioncatcher-build.py' in order to fix this!
  ....................
```

What should I do to resolve it?

**Comment by MaxUlysse** [comment]
Hi @valleema I more recently got more involved into this project, and I'm currently focusing on the #54 issue.
I'll look into that first thing after.

**Comment by valleema** [comment]
Great! And the #54 issue is quite interesting to add, I reckon.

**Comment by matq007** [comment]
Hey @valleema are you running nf-core/rnafusion:1.0.2? Everything should be compatible

**Comment by valleema** [comment]
Hi @matq007, yes I am running the "downloaded-yesterday". In the Nextflow code, the download points to a v90 reference, and only the v98 is available. 

That's why I manually downloaded the v98, following your help pages.

**Comment by matq007** [comment]
Ah, I finally see the problem. Damn.. the author removed the old reference. Hmmm... The only option currently that I can think about is to create your own singularity image with the latest `fusioncatcher` tool.

new environment file
```
name: fusioncatcher
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::fusioncatcher=1.20
```
and then `cd tools && build.sh fusioncatcher` which will generate docker container which can be afterwards transformed into singularity image.

**Comment by valleema** [comment]
Yes, building my own image was on my mind as well... Tough task, right now as I am not root of any machines around. I might find a way, but it could be a better call to let you time to update the image, for the new users of this pipeline as well.

What do you think?

**Comment by valleema** [comment]
Or... If you have them somewhere, make the v90 files available to download. It could be a quick solution.

**Comment by matq007** [comment]
I have fixed the issue on the `dev` branch. There is a new container on dockerhub which you can download and convert to singularity image. One thing to note is that in order to run `fusioncatcher` you have to run `fusioncatcher.py <commands>`.

**Comment by valleema** [comment]
So, it needs to be 1.20 here : 

https://github.com/nf-core/rnafusion/blob/5fea38c304210d85c81e0335663697417d85690d/nextflow.config#L14

https://github.com/nf-core/rnafusion/blob/d4a622c2e24148c568994f3d019b2a3b5a014e17/example/custom-singularity.config#L15

https://github.com/nf-core/rnafusion/blob/d4a622c2e24148c568994f3d019b2a3b5a014e17/example/custom-docker.config#L15

But so far, so good, it runs! Thanks a lot!!!

**Comment by matq007** [comment]
Ah, thanks for pointing out. We will make these changes once we bump the version

**Comment by valleema** [comment]
Great. Thanks a lot for your help and your quick solutions!
